#ifndef CORNOBJ_H
#define CORNOBJ_H

/* Generated from asm/CORNOBJ.EQU. */

// OBJECTS.EQU
// 
// COPYRIGHT (C) 1994 TV GAMES, INC.
// ALL RIGHTS RESERVED
// 
// Generated by PComp v2.41
// 
// num_palettes	.set	1
// cornpops_p          	.set	0
// 
// num_objects	.set	1

// asm: cornpops            	.set	0C14482h
#define cornpops 0x0C14482

// asm: cornpops_I          	.set	03D2Ch
#define cornpops_I 0x03D2C

// asm: CORNPAL	.set	0C14400h
#define CORNPAL 0x0C14400

// num_sections	.set	1
// corn                	.set	0AF4B00h	;1DC0
// asm: 	.globl	_SECcorn
extern int _SECcorn[];

#endif /* CORNOBJ_H */
