#ifndef GLOBALS_H
#define GLOBALS_H

#include "../core/port.h"

typedef struct LOAD_SECTION_REQ_ARG LOAD_SECTION_REQ_ARG;

/* Generated from asm/GLOBALS.EQU. */

// globals.equ
//
// obj.asm

// asm:  .globl COMM_DRONE_PTR
extern OBJ* COMM_DRONE_PTR;

//
// auto generated by tvg/brief
//
//

// attracta.asm
// asm:  .globl _ATTR_MODE
extern int _ATTR_MODE;

// asm:  .globl TITLES,TEXTTABSI
extern const char* TITLES[];

#define TEXTTABSI TEXTTABS

// attrdrne.asm
// asm:  .globl ATTRWAVE,LOAD_ATTR_LEG
extern int ATTRWAVE;

// asm:  .globl BABE_CONTROL
extern int BABE_CONTROL;

// backgrnd.asm
// asm:  .globl RACE_STARTING_POINTSI,RACE_STARTING_POINTS
#define RACE_STARTING_POINTSI RACE_STARTING_POINTS

extern int RACE_STARTING_POINTS[];

extern int FINISH_LINE;

// asm:  .globl DRIVE_LIST,CAR_LIST,BUILD_LIST,SIGN_LIST,GROUND_LIST
extern OBJ* DRIVE_LIST;

extern OBJ* CAR_LIST;

extern OBJ* SIGN_LIST;

extern OBJ* GROUND_LIST;

extern VEHTAB VEHICLE_TABLE[];

// asm:  .globl STARTSECTION,START_POS,START_RADY
extern int STARTSECTION;

extern c3x_reg_t START_POS[];

extern c3x_reg_t START_RADY;

// asm:  .globl DGROUPSI
#define DGROUPSI DGROUPS

// asm:  .globl DGROUPS
extern DGROUP_ENTRY DGROUPS[];

// asm:  .globl DGROUP_COUNT
extern int DGROUP_COUNT;

// asm:  .globl DGROUP_AW
extern tyco_stream_t DGROUP_AW;

// asm:  .globl DYNALIST_TRUEBEGIN
extern OBJ* DYNALIST_TRUEBEGIN;

// asm:  .globl DYNALIST_BEGIN
extern OBJ* DYNALIST_BEGIN;

// asm:  .globl DYNALIST_END
extern OBJ* DYNALIST_END;

// asm:  .globl STARTS
extern OBJ* STARTS;

// asm:  .globl SECTIONIDX
extern int SECTIONIDX;

// asm:  .globl TYCO_TRACK
extern tyco_stream_t TYCO_TRACK;

// asm:  .globl TYCO_TRACK_NTL
extern tyco_stream_t TYCO_TRACK_NTL;

extern OBJ* SINGLE_SECTION_TEMPPTR;

// bssstart.asm
// asm:  .globl BSSSTART
extern int BSSSTART;

// asm:  .globl ETIME
extern int ETIME;

// asm:  .globl DO_FOLDFLAG
extern int DO_FOLDFLAG;

// asm:  .globl DID_TIMED_OUT
extern int DID_TIMED_OUT;

// asm:  .globl FULLSETUP_TABLEI,BONUS_POSTLAUNCHI
#define FULLSETUP_TABLEI FULLSETUP_TABLE
extern void (*FULLSETUP_TABLE[])(void);

#define BONUS_POSTLAUNCHI BONUS_POSTLAUNCH
extern void_func_ptr BONUS_POSTLAUNCH[];

// asm:  .globl CHALLENGE_RACE
extern int CHALLENGE_RACE;

// asm:  .globl NEXT_STARTUP,BONUS_WAVE
extern int NEXT_STARTUP;

extern int BONUS_WAVE;

// asm:  .globl MAXMPH,CAR_COLLS,MISC_COLLS
extern int MAXMPH;

// asm:  .globl BONUS_TABLEI
#define BONUS_TABLEI BONUS_TABLE

// asm:  .globl GAMETRAKI,GAMETRAK
#define GAMETRAKI GAMETRAK

extern int GAMETRAK[];

// asm:  .globl LEG_NAMESI,LEG_NAMES
#define LEG_NAMESI LEG_NAMES

extern const char* LEG_NAMES[];

// asm:  .globl HELI_ABORT
extern int HELI_ABORT;

// asm:  .globl CMOSI,HSTD_PAGEI,ALL_TIME_HSTDI,DAILY_HSTDI
#define CMOSI CMOS

#define SCOLLTABI SCOLLTAB

// asm:  .globl BOXSCRAMI
#define BOXSCRAMI BOXSCRAM

// asm:  .globl FLYCOLLPI
#define FLYCOLLPI FLYCOLLP

// coin.asm
// asm:  .globl ICF
extern int ICF;

// asm:  .globl COIN_TABLEI
#define COIN_TABLEI COIN_TABLE

// asm:  .globl COINOFF
extern int COINOFF;

extern int VOLUME_ACTIVE;

// asm:  .globl CMOS_WP_WORD_SHADOW,COIN_COUNTER1,COIN_COUNTER2
extern int CMOS_WP_WORD_SHADOW;

extern int COIN_COUNTER1;

extern int COIN_COUNTER2;

// asm:  .globl COUNTER_IDX,COUNTER_MODE
extern int COUNTER_IDX;

extern int COUNTER_MODE;

// asm:  .globl HARD_SECTION_LOAD
extern int HARD_SECTION_LOAD;

// asm:  .globl DECOMP_ACTIVE
extern int DECOMP_ACTIVE;

// asm:  .globl BOOT_PACIFY_SCREEN_P
extern int BOOT_PACIFY_SCREEN_P;

// asm:  .globl PREVX,DELTA
extern int PREVX;

extern int DELTA;

// asm:  .globl TRANSMISSION_ACTIVE
extern int TRANSMISSION_ACTIVE;

// asm:  .globl PLY2CAR
extern OBJ* PLY2CAR;

// asm:  .globl OM_POSITION
extern int OM_POSITION;

// asm:  .globl OM_DIFF
extern c3x_reg_t OM_DIFF;

// asm:  .globl COINDROP
extern int COINDROP;

// asm:  .globl OM_RACE_MODE
extern int OM_RACE_MODE;

// asm:  .globl OM_BSYNC
extern int OM_BSYNC;

// asm:  .globl BSYNC
extern int BSYNC;

// asm:  .globl OM_HIDDEN_ON
extern int OM_HIDDEN_ON;

// asm:  .globl IGNORE_UPDATES
extern int IGNORE_UPDATES;

// asm:  .globl COMMQ_TMP_BUFFI
#define COMMQ_TMP_BUFFI COMMQ_TMP_BUFF

// asm:  .globl LINKEDP
extern int LINKEDP;

// asm:  .globl MY_LINKWAIT
extern int MY_LINKWAIT;

// asm:  .globl OM_LINKWAIT
extern int OM_LINKWAIT;

// asm:  .globl HEAD2HEAD_ON
extern int HEAD2HEAD_ON;

// asm:  .globl OLD_OM_ATTR_MODE
extern int OLD_OM_ATTR_MODE;

// asm:  .globl OM_ATTR_MODE
extern int OM_ATTR_MODE;

// asm:  .globl SEND_BUFFER_A_LEN
extern int SEND_BUFFER_A_LEN;

// asm:  .globl SEND_BUFFER_A
extern int SEND_BUFFER_A[];

// asm:  .globl SEND_BUFFER_AI
#define SEND_BUFFER_AI SEND_BUFFER_A

// asm:  .globl RECEIVE_BUFFER
extern int RECEIVE_BUFFER[];

// asm:  .globl OM_MODE,OM_CHOSEN_RACE,OM_VEHICLE
extern int OM_MODE;

extern int OM_CHOSEN_RACE;

extern int OM_VEHICLE;

// asm:  .globl OM_STATE,MY_STATE
extern int OM_STATE;

extern int MY_STATE;

// cusa.asm
// asm:  .globl FRAMRATE
extern int FRAMRATE;

// asm:  .globl COMMINTM
extern int COMMINTM;

// asm:  .globl CLEARRDY
extern int CLEARRDY;

// asm:  .globl SWRAM
extern int SWRAM[];

// asm:  .globl NOAERASE
extern int NOAERASE;

// asm:  .globl BUTTON_STATUS
extern int BUTTON_STATUS;

// asm:  .globl INFRAMES,NFRAMES
extern int INFRAMES;

extern int NFRAMES;

// asm:  .globl _newbut
extern int _newbut;

// asm:  .globl SWITCHBUTS
extern int SWITCHBUTS;

// asm:  .globl DIAG_ACTIVE
extern int DIAG_ACTIVE;

// asm:  .globl GAME_TIMER
extern c3x_reg_t GAME_TIMER;

// asm:  .globl ST_POLYGONS
extern int ST_POLYGONS;

// asm:  .globl ST_VERTICES
extern int ST_VERTICES;

// asm:  .globl ST_OBJECTS
extern int ST_OBJECTS;

// asm:  .globl SWITCHBUTS,BGNDCOLA,DIAG_ACTIVE,GAME_TIMER
extern int BGNDCOLA;

// asm:  .globl _MODE,SYSCNTL,_pot0,_pot1,_pot2
extern int _MODE;

extern int SYSCNTL;

extern int _pot0;

extern int _pot1;

extern int _pot2;

// asm:  .globl RDPOT,_systime,_gametime,_sectime
extern int RDPOT;

extern int _sectime;

// asm:  .globl CLEARRDY,NOAERASE,DISPLAY_PAGE
extern int DISPLAY_PAGE;

// asm:  .globl NOSWAP
extern int NOSWAP;

// asm:  .globl FRAMRATE,TIMECLR
extern int TIMECLR;

// asm:  .globl VERSION_STAMP
extern const char VERSION_STAMP[];

// date.asm
// asm:  .globl DATE_STAMP
extern const char DATE_STAMP[];

// asm:  .globl DRONENUM
extern int DRONENUM;

// asm:  .globl SMOKE_COUNT
extern int SMOKE_COUNT;

// asm:  .globl DRONE_COUNT,FINISHED_DRONES,MIN_TRACK_TIME
extern int DRONE_COUNT;

extern int MIN_TRACK_TIME;

// asm:  .globl DD_SLP,DD_VAR,DD_MAX_DRONES
extern int DD_SLP;

extern int DD_VAR;

extern int DD_MAX_DRONES;

// asm:  .globl DRONE_DISPATCH_P
extern int DRONE_DISPATCH_P;

// asm:  .globl MODELTABI,TEXTTABSI,TABING
#define MODELTABI MODELTAB

extern c3x_f32_t TABING[];

// asm:  .globl COCONUT_COUNT
extern int COCONUT_COUNT;

// asm:  .globl RAND,_MODE
extern int RAND;

// asm:  .globl OACTIVE,OFREE,OACTIVE_PRIORITY,IDLE_LIST
extern OBJ* OACTIVE;

extern OBJ* OFREE;

extern OBJ* IDLE_LIST;

// asm:  .globl OACTIVEI,OACTIVE_PRIORITYI,IDLE_LISTI
#define OACTIVEI OACTIVE

#define OACTIVE_PRIORITYI OACTIVE_PRIORITY

#define IDLE_LISTI IDLE_LIST

// asm:  .globl CAMERAPOSI,CAMERARADI,CAMERAMATRIXI
extern VECTOR _CAMERAPOS;
#define CAMERAPOSI _CAMERAPOS

extern VECTOR _CAMERARAD;
#define CAMERARADI _CAMERARAD

extern MATRIX _CAMERAMATRIX;
#define CAMERAMATRIXI _CAMERAMATRIX

// asm:  .globl POSTERMATI
extern MATRIX POSTERMATRIX;
#define POSTERMATI POSTERMATRIX

// asm:  .globl DRIVE_LISTI,CAR_LISTI,SIGN_LISTI,GROUND_LISTI
#define DRIVE_LISTI DRIVE_LIST

#define CAR_LISTI CAR_LIST

#define SIGN_LISTI SIGN_LIST

#define GROUND_LISTI GROUND_LIST

// asm:  .globl LOCTEMPER_MATI
#define LOCTEMPER_MATI LOCTEMPER_MAT
extern MATRIX LOCTEMPER_MAT;

// asm:  .globl LIGHTIY
extern VECTOR _LIGHT;
// extern uintptr_t LIGHTIY;

// asm:  .globl transmatrixI,transvectorYI
#define transmatrixI ROTATION_MATRIX

// extern uintptr_t transvectorYI;

// asm:  .globl BLOWLISTI,tmpmatI,tmpmatY,INVTABI
#define BLOWLISTI BLOWLIST
extern c3x_f32_t BLOWLIST[];

#define tmpmatI TMPMAT

// extern uintptr_t tmpmatY;

#define INVTABI INVTAB

// asm:  .globl SCRNHXI,SCRNHYI
extern c3x_reg_t SCRNHXI;

extern c3x_reg_t SCRNHYI;

// asm:  .globl LOW_TOSS_LEVELI,LOW_CLIP_LEVELI,HIGH_CLIP_LEVELI,HIGH_CLIP_LEV8,MAXZI
extern int HIGH_CLIP_LEV8;

// asm:  .globl CENTSI,_PALLISTI,FASTSTKI
#define _PALLISTI _PALLIST
extern tPALLIST_ENTRY _PALLIST[];

#define FASTSTKI FASTSTK

// asm:  .globl _ACMAP,_ARPS,_AIVI,_ADDRL,_ACNTL
extern int _ACMAP;

extern int _ARPS[];

extern int _AIVI[];

extern int _ADDRL;

extern int _ACNTL;

// asm:  .globl MATRIXAI,MATRIXBI,MATRIXCI,VECTORAI,VECTORBI,VECTORCI,VECTORDI
#define MATRIXAI _MATRIXA

#define MATRIXBI _MATRIXB

#define MATRIXCI _MATRIXC

#define VECTORAI _VECTORA

#define VECTORBI _VECTORB

#define VECTORCI _VECTORC

#define VECTORDI _VECTORD

// asm:  .globl ASHADOW
extern uintptr_t ASHADOW;

// asm:  .globl SOFT_AUDIT
extern int SOFT_AUDIT;

// asm:  .globl bufferI
#define bufferI buffer

// asm:  .globl NULLSTR
extern const char NULLSTR[];

// asm:  .globl SCREENWIPE_DONE
extern int SCREENWIPE_DONE;

// hud.asm
// asm:  .globl MOVEIN_OFFSET
extern int MOVEIN_OFFSET;

// asm:  .globl POSITION
extern int POSITION;

// asm:  .globl _countdown,SCORE,_MPH
extern int _countdown;

extern int SCORE;

extern int _MPH;

// asm:  .globl alloc_section
#define alloc_section HARDalloc_section

// asm:  .globl COUNTDOWN_BUFI
#define COUNTDOWN_BUFI COUNTDOWN_BUF

// asm:  .globl INFIN_CORRECT
extern c3x_reg_t INFIN_CORRECT;

// asm:  .globl VAR_ROAD_KFACTOR
extern c3x_reg_t VAR_ROAD_KFACTOR;

// asm:  .globl MAXMPH_COUNT
extern int MAXMPH_COUNT;

// asm:  .globl BONUS_WAITFLAG
extern int BONUS_WAITFLAG;

// asm:  .globl OM_BONUS_WAITFLAG
extern int OM_BONUS_WAITFLAG;

// asm:  .globl H2H_FLAGSTATE
extern int H2H_FLAGSTATE;

// asm:  .globl REAL_CHECKPOINTS
extern int REAL_CHECKPOINTS;

// asm:  .globl FIRST_RACE
extern int FIRST_RACE;

// asm:  .globl GAMEDIFF
extern c3x_reg_t GAMEDIFF;

// asm:  .globl CHECKPOINT_NUM
extern int CHECKPOINT_NUM;

// asm:  .globl CHOSEN_VEHICLE
extern int CHOSEN_VEHICLE;

// asm:  .globl CHOSEN_TRANSMISSION,CHOICENOW
extern int CHOSEN_TRANSMISSION;

// asm:  .globl POSES
extern int POSES;

// asm:  .globl END_OF_GAMEP
extern int END_OF_GAMEP;

extern int _timer;

// asm:  .globl CHOOSENCAR
extern int CHOOSENCAR;

// asm:  .globl DIRTY_SHARED
extern int DIRTY_SHARED;

// asm:  .globl LASTCHOICE
extern int LASTCHOICE;

// asm:  .globl START_NOW_P
extern int START_NOW_P;

// asm:  .globl START_HIT
extern int START_HIT;

// asm:  .globl CHOSEN_RACE
extern int CHOSEN_RACE;

// invtab30.asm
// asm:  .globl INVTAB
extern c3x_f32_t* INVTAB;

// asm:  .globl LEG_MAP,LEG_MAPI
extern LEG_PAYLOAD LEG_MAP[];

#define LEG_MAPI LEG_MAP

// asm:  .globl FINISH_ID
extern int FINISH_ID;

// asm:  .globl HALFPII,PII,TWOPII
extern c3x_reg_t HALFPII;

extern c3x_reg_t PII;

extern c3x_reg_t TWOPII;

#define FIND_YMATRIX _find_Ymatrix

// map.asm
// asm:  .globl THIS_MACHINE_AHEAD
extern int THIS_MACHINE_AHEAD;

// asm:  .globl STOPWATCH,STOPWATCH_CNTL
extern int STOPWATCH;

extern int STOPWATCH_CNTL;

// asm:  .globl MOTION_RCV_TIKS
extern int MOTION_RCV_TIKS;

// asm:  .globl MOTION_STOP_HIT
extern int MOTION_STOP_HIT;

// asm:  .globl CHECKPOINT_TIME_BONUS
extern int CHECKPOINT_TIME_BONUS;

// plyr.asm
// asm:  .globl _plyr1
extern int _plyr1;

// asm:  .globl STEERMX,STEERMN,STEERCT,STEERFR,PEDALMX,PEDALMN
extern c3x_reg_t STEERMX;

extern c3x_reg_t STEERMN;

extern c3x_reg_t STEERCT;

extern c3x_reg_t STEERFR;

extern c3x_reg_t PEDALMX;

extern c3x_reg_t PEDALMN;

// asm:  .globl PLYSTAT,PLYCAR,PLYPROC,PLYCBLK
extern int PLYSTAT;

extern OBJ* PLYCAR;

extern PROC* PLYPROC;

extern CARBLK* PLYCBLK;

extern int CAMVIEW;

// asm:  .globl OFFROAD_TMR,OVELNADD
extern int OFFROAD_TMR;

// asm:  .globl ZOOM,ZOOMI,ZOOMD
#define ZOOMI ZOOMRAM

extern c3x_reg_t ZOOMD;

// racer.asm
// asm:  .globl RACER_PTRI

// asm:  .globl NOLONG_VEHICLES
extern int NOLONG_VEHICLES;

extern OBJ* ROAD_DEBRIS;

// asm:  .globl ROADKILL_SOUND_TIMER
extern c3x_reg_t ROADKILL_SOUND_TIMER;

// asm:  .globl DIV_F,DIV_F30
#define DIV_F DIV_F30

// asm:  .globl DIV_I,DIV_I30
#define DIV_I DIV_I30

#define FLYTRAINPI FLYTRAINP

// asm:  .globl FREEZE_IT
extern int FREEZE_IT;

// setups.asm
// asm:  .globl LOADSECTION_TABLEI
#define LOADSECTION_TABLEI LOADSECTION_TABLE
extern void (*LOADSECTION_TABLE[])(void);

extern int TIRE_SMOKE_COUNT;

// asm:  .globl SNDSTR,SNDSTRI
extern int SNDSTR[];

#define SNDSTRI SNDSTR

extern int TUNE_IDX;

// asm:  .globl SNDTABI
#define SNDTABI SNDTAB

// asm:  .globl IN_RESET_MODE
extern int IN_RESET_MODE;

// asm:  .globl EPALR,EPALL,EPALRR,EPALRL
extern tPAL* EPALR;

extern tPAL* EPALL;

// asm:  .globl DOORLISTI,DOORLIST
#define DOORLISTI DOORLIST

extern int DOORLIST;

// util.asm
// asm:  .globl RAND,CRTCTLRAM,ACTIVE_SCREEN
extern int CRTCTLRAM;

extern int ACTIVE_SCREEN;

// asm:  .globl FASTCLR0,FASTCLR1
#define FASTCLR0 FASTCLR1

// asm:  .globl DYNALIST,DYNAFREE,NULL
extern DYNAOBJ DYNALIST[];

extern DYNAOBJ* DYNAFREE;

extern int NULL_;
#define NULLI NULL_;

// asm:  .globl CARLIST,CARFREE,CAR_COUNT
extern CARBLK CARLIST[];

// wave.asm
// asm:  .globl LOADED
extern int LOADED;

// asm:  .globl FIXEDPAL
extern tPAL FIXEDPAL;

// asm:  .globl ILLUM_PAL
extern tPAL ILLUM_PAL;

// asm:  .globl TEASE_COUNT,ATTR_MODEL
extern int TEASE_COUNT;

extern int ATTR_MODEL;

// wheel.asm
// asm:  .globl WHEELPWR,WHEELPOS,WHEELMAX,WHEELVEL
extern int WHEELPWR;

extern int WHEELPOS;

extern c3x_reg_t WHEELMAX;

extern int WHEELVEL;

extern int POSE;

// asm:  .globl VANITY
void VANITY(void);

void LOAD_ATTR_LEG(void);

// audits.asm
// asm:  .globl AUDIT_DISPLAY
void AUDIT_DISPLAY(void);

// babe.asm
// asm:  .globl CROWD_IT
void CROWD_IT(void);

// asm:  .globl BABE_TROPHY
void BABE_TROPHY(void);

// asm:  .globl BABE_WAVEFLAG
void BABE_WAVEFLAG(PROC* p);

// asm:  .globl LOAD_SINGLE_SECTION_OFFSET
void LOAD_SINGLE_SECTION_OFFSET(void);

// asm:  .globl FIND_STARTING_VALUES
void FIND_STARTING_VALUES(void);

// asm:  .globl LOAD_TUNNEL,FINISH_LINE
void LOAD_TUNNEL(void);

// asm:  .globl BGD_INIT
void BGD_INIT(void);

// asm:  .globl LOAD_SINGLE_SECTION,SINGLE_SECTION_TEMPPTR
OBJ* LOAD_SINGLE_SECTION(LOAD_SINGLE_SECTION_GROUP* rom_group /*AR2*/);

// asm:  .globl GET_XZ_DISTANCE
c3x_reg_t GET_XZ_DISTANCE(VECTOR* v1 /*AR2*/, VECTOR* v2 /*R2*/);

// asm:  .globl AMBIENCE_SOUND
void AMBIENCE_SOUND(void);

// asm:  .globl KILL_THEM
void KILL_THEM(void);

// asm:  .globl BLINK_FREEBE
void BLINK_FREEBE(PROC* p);

// asm:  .globl TIMED_OUT
void TIMED_OUT(void);

// asm:  .globl BONUS1,BONUS2,BONUS3,BONUS4
void BONUS1(void);

void BONUS2(void);

void BONUS3(void);

void BONUS4(void);

// asm:  .globl BONUS5,BONUS6,BONUS7,BONUS8
void BONUS5(void);

void BONUS6(void);

void BONUS7(void);

void BONUS8(void);

// asm:  .globl BONUS9,BONUS10,BONUS11,BONUS12
void BONUS9(void);

void BONUS10(void);

void BONUS11(void);

void BONUS12(void);

// asm:  .globl BONUS13,BONUS14
void BONUS13(void);

void BONUS14(void);

// chopper.asm
// asm:  .globl CHOPPER
void CHOPPER(void);

// asm:  .globl GET_CLOSEST_TRAK
void GET_CLOSEST_TRAK(void);

// cmos.asm
// asm:  .globl RESET_DAILY_CMOS,HSTDEC
void HSTDEC(void);

// asm:  .globl _wr_cw,_rd_cw
void _wr_cw(word_addr_t addr, int value);

int _rd_cw(word_addr_t addr);

// asm:  .globl _CARV0,_CARVCT
CARBLK* _CARV0(OBJ* obj /*AR4*/, int vehicle /*R0*/);

// asm:  .globl _PLAYER_ROAD_COLL,CAR_ROAD_COLL
void CAR_ROAD_COLL(OBJ* obj /*AR4*/, CARBLK* carblk /*R3*/);

// asm:  .globl _coll_road
int _coll_road(OBJ* road_obj /*AR2*/, VECTOR* point /*AR4*/, c3x_reg_t* out_road_delta /*R0*/);

// asm:  .globl _obj_coll,COLLIDE
int _obj_coll(OBJ* obj /*AR2*/, VECTOR* point /*R2*/);

// asm:  .globl _makbox
void _makbox(OBJ* obj /*AR4*/);

// asm:  .globl COLSCC
void COLSCC(void);

// asm:  .globl COLSCAN,COLSCPRC
void COLSCAN(void);

// asm:  .globl BOXSCAN
void BOXSCAN(void);

// asm:  .globl OBJSCAN
int OBJSCAN(OBJ* obj /*AR4*/, c3x_reg_t* out_road_delta /*R0*/);

// asm:  .globl CAMSCAN
int CAMSCAN(VECTOR* point /*AR4*/, c3x_reg_t* out_road_delta /*R0*/);

// asm:  .globl COLCHK
void COLCHK(void);

// asm:  .globl ROADSCAN,DRONESND,DRONESND1,FLYCAR1,SCOLLTABI
void ROADSCAN(OBJ* obj /*AR4*/, CARBLK* carblk /*R3*/);

void DRONESND(void);

void DRONESND1(void);

// asm:  .globl COLSGCK
void COLSGCK(OBJ* car_obj /*AR0*/, OBJ* sign_obj /*AR1*/);

// asm:  .globl SERV_COIN
void SERV_COIN(void);

// asm:  .globl INSERT_COINS
void INSERT_COINS(void);

// asm:  .globl COIN1,COIN2,CHECK_CREDITS
void COIN1(void);

void COIN2(void);

// asm:  .globl COIN3,COIN4
void COIN3(void);

void COIN4(void);

// asm:  .globl VOLUME_DISPLAY,VOLUME_ACTIVE
void VOLUME_DISPLAY(void);

// asm:  .globl INSERT_MORE_COINS
void INSERT_MORE_COINS(void);

// asm:  .globl COIN_COUNTER
void COIN_COUNTER(void);

// asm:  .globl GETCOINTXT
char** GETCOINTXT(void);

// asm:  .globl INIT_CUSTOM_COIN
void INIT_CUSTOM_COIN(void);

// comp.asm
// asm:  .globl DECOMPRESS
// void DECOMPRESS(word_addr_t source_addr, word_addr_t dest_addr);

// asm:  .globl DECOMPRESS_PROC
void DECOMPRESS_PROC(void);

// asm:  .globl LOAD_SECTION_REQ
void LOAD_SECTION_REQ(LOAD_SECTION_REQ_ARG* section_control);

// asm:  .globl CLRONE
void CLRONE(void);

// asm:  .globl SETONE
void SETONE(void);

// asm:  .globl COMM_ENABLE_INT2
void COMM_ENABLE_INT2(void);

// asm:  .globl COMM_MASTER_SEND_SYNC
void COMM_MASTER_SEND_SYNC(void);

// asm:  .globl COMM_INIT
void COMM_INIT(void);

// asm:  .globl COMM_ROUTINE
void COMM_ROUTINE(void);

// asm:  .globl COMM_IRQ
void COMM_IRQ(void);

// commdrne.asm
// asm:  .globl COMM_DRONE_PTR_SORT
void COMM_DRONE_PTR_SORT(void);

// asm:  .globl COMM_DRONE
void COMM_DRONE(void);

// commq.asm
// asm:  .globl SEND_ATTRSND
void SEND_ATTRSND(void);

// asm:  .globl SEND_COINDROP
void SEND_COINDROP(void);

// asm:  .globl SEND_WAVEFL_GO
void SEND_WAVEFL_GO(void);

// asm:  .globl SEND_WAVEFL_SET
void SEND_WAVEFL_SET(void);

// asm:  .globl SEND_WAVEFL_READY
void SEND_WAVEFL_READY(void);

// asm:  .globl CLEAR_LINK
void CLEAR_LINK(void);

// asm:  .globl SEND_LINKCANCELLED
void SEND_LINKCANCELLED(void);

// asm:  .globl COMMQ_READY_TO_SEND
void COMMQ_READY_TO_SEND(void);

// asm:  .globl COMMQ_PACKET_INIT
void COMMQ_PACKET_INIT(void);

// asm:  .globl SEND_CHECKPOINT
void SEND_CHECKPOINT(void);

// asm:  .globl SEND_START_GAME
void SEND_START_GAME(void);

// asm:  .globl SEND_END_GAME
void SEND_END_GAME(void);

// asm:  .globl SEND_VEHICLE
void SEND_VEHICLE(void);

// asm:  .globl ENABLEGIE
void ENABLEGIE(void);

// asm:  .globl _c_int00
void _c_int00(void);

// asm:  .globl VERIFY_CODE_INTEGRITY
void VERIFY_CODE_INTEGRITY(void);

// asm:  .globl FEED_WATCHDOG
void FEED_WATCHDOG(void);

// asm:  .globl INT0   ;DISPLAY INT
void INT0(void);

// asm:  .globl COLD_ENTER
void COLD_ENTER(void);

// asm:  .globl WAIT_FOR_VBLANK
void WAIT_FOR_VBLANK(void);

// asm:  .globl CHECKDIAG
void CHECKDIAG(void);

// asm:  .globl FIFO_RESET
void FIFO_RESET(void);

// asm:  .globl CLR_RAM
void CLR_RAM(void);

// asm:  .globl ATTRACT_DELTA
void ATTRACT_DELTA(PROC* p);

// drones.asm
// asm:  .globl DRONE_CLR
void DRONE_CLR(void);

// asm:  .globl DRONE_PTR_ADD
void DRONE_PTR_ADD(void);

// asm:  .globl FIND_PLAYERS_POSITION,POSITION_FINDER
void FIND_PLAYERS_POSITION(OBJ* player_obj /*AR4*/, CARBLK* player_carblk /*AR5*/);

void POSITION_FINDER(PROC* p);

// asm:  .globl INIT_DRONES,ADD_DRONE,FREE_DRONE
void INIT_DRONES(void);

void ADD_DRONE(OBJ* obj /*AR4*/);

void FREE_DRONE(void);

// asm:  .globl PLYR_RIDE_RIGHT,DRONE_RIDE_RIGHT
c3x_reg_t PLYR_RIDE_RIGHT(void);

c3x_reg_t DRONE_RIDE_RIGHT(OBJ* obj /*AR4*/, CARBLK* carblk /*AR5*/);

// asm:  .globl EXP_PUFF,SMOKE_PUFF,DROP_COCONUTS
void EXP_PUFF(void);

void SMOKE_PUFF(void);

void DROP_COCONUTS(void);

// asm:  .globl SIGMA_DISPATCHER,RHO_DISPATCHER
void SIGMA_DISPATCHER(PROC* p);

void RHO_DISPATCHER(PROC* p);

// asm:  .globl DIST_TO_PLYR
void DIST_TO_PLYR(void);

// dirq.asm
// asm:  .globl DIRQ
void DIRQ(void);

// diag.asm
// asm:  .globl ENTER_DIAG
void ENTER_DIAG(void);

// asm:  .globl HARD_LOAD_DIAGPAL
void HARD_LOAD_DIAGPAL(void);

// asm:  .globl TOEXIT
void TOEXIT(void);

// asm:  .globl SETUP_DIAG_SCREEN
void SETUP_DIAG_SCREEN(void);

// effects.asm
// asm:  .globl SCREENWIPE_OPEN
void SCREENWIPE_OPEN(void);

// asm:  .globl SCREENWIPE_OPEN_PRC
void SCREENWIPE_OPEN_PRC(void);

// asm:  .globl SCREENWIPE_CLOSE
void SCREENWIPE_CLOSE(void);

// asm:  .globl SCREENWIPE_CLOSE_PRC
void SCREENWIPE_CLOSE_PRC(void);

// asm:  .globl SCREENWIPE_OPEN_PRC_FAST
void SCREENWIPE_OPEN_PRC_FAST(void);

// flame.asm
// asm:  .globl FLAME_PRC,FLAMESORT,GETCARBODY
void FLAME_PRC(void);

void FLAMESORT(void);

void GETCARBODY(void);

// asm:  .globl FIND_NEXT_OBJ
OBJ* FIND_NEXT_OBJ(OBJ* obj /*AR0*/, int oid /*R1*/);

// font1a.asm
// asm:  .globl _outtextxyc
void _outtextxyc(const char* string, int x, int y, int color);

// asm:  .globl _itoa,_itoaLZ
void _itoa(char* string_space /*AR2*/, int number /*R2*/);

void _itoaLZ(void);

// asm:  .globl _ftoa
void _ftoa(void);

// asm:  .globl _pixel
void _pixel(int x, int y, int color);

// asm:  .globl _fill
void _fill(int x1, int y1, int x2, int y2, int color);

// asm:  .globl HEX2ASC
void HEX2ASC(void);

// hottub.asm
// asm:  .globl HOTTUB_SCENE
void HOTTUB_SCENE(void);

// hpmath.c
// asm:  .globl _HPcos,_HPsin
c3x_reg_t _HPsin(c3x_reg_t x);
c3x_reg_t _HPcos(c3x_reg_t x);

// hstdp.asm
// asm:  .globl DISPLAY_HIGH_SCORES
void DISPLAY_HIGH_SCORES(PROC* p);

// asm:  .globl ENTERTEXT
void ENTERTEXT(void);

// asm:  .globl ENTER_INITIALS
void ENTER_INITIALS(void);

// asm:  .globl MIDWAYSPINENTER
void MIDWAYSPINENTER(void);

// asm:  .globl LOGO_PROC
void LOGO_PROC(PROC* p);

// asm:  .globl RBMATTR_CHECK
void RBMATTR_CHECK(void);

// asm:  .globl INTO_TABLE_P
void INTO_TABLE_P(void);

// asm:  .globl MOVEIN_HUD_EQUIP
void MOVEIN_HUD_EQUIP(void);

// asm:  .globl MOVEOUT_HUD_EQUIP
void MOVEOUT_HUD_EQUIP(void);

// asm:  .globl HARDalloc_section
void HARDalloc_section(tSECTION_ALLOC sec);

// asm:  .globl INFINITY
void INFINITY_CUSA(void);

// asm:  .globl HUD
void HUD(void);

// asm:  .globl dealloc_section
void dealloc_section(tSECTION_ALLOC sec /*AR2*/);

// asm:  .globl FILL_PLOT
void FILL_PLOT(void);

// asm:  .globl FILL_DITHER
void FILL_DITHER(void);

// intro.asm
// asm:  .globl ISSUE_STARTGAME_TSEL
void ISSUE_STARTGAME_TSEL(void);

// asm:  .globl PLYR_INTRO
void PLYR_INTRO(void);

// asm:  .globl ISSUE_STARTGAME
void ISSUE_STARTGAME(void);

// asm:  .globl WAIT_FOR_CHALLENGER
void WAIT_FOR_CHALLENGER(void);

// asm:  .globl LOGO_SMALL
void LOGO_SMALL(void);

// asm:  .globl HEAD2HEAD_LOGO_WAIT
void HEAD2HEAD_LOGO_WAIT(void);

// asm:  .globl HEAD2HEAD_LOGO
void HEAD2HEAD_LOGO(void);

// asm:  .globl CHOOSE_NEXT_RACE
void CHOOSE_NEXT_RACE(void);

// asm:  .globl INIT_GAMELEG
void INIT_GAMELEG(void);

// asm:  .globl INIT_PEDALCHK,PEDALCHK
void INIT_PEDALCHK(void);

void PEDALCHK(void);

// asm:  .globl GETCHOICE
void GETCHOICE(void);

// asm:  .globl CPOINT_LIGHT
void CPOINT_LIGHT(PROC* p);

// asm:  .globl _debug,_start
void _debug(void);

void _start(void);

// asm:  .globl _timeout,_timer
void _timeout(PROC* p);

// asm:  .globl SET_ATTR,CYCLE_ATTR
void SET_ATTR(void);
void CYCLE_ATTR(void);

// asm:  .globl INTROTIMER,RACESEL_TIMER
void INTROTIMER(void);

void RACESEL_TIMER(void);

// asm:  .globl ENDPLAYER
void ENDPLAYER(void);

// asm:  .globl INSMORE
void INSMORE(void);

// asm:  .globl LOAD_SHARED
void LOAD_SHARED(void);

// asm:  .globl TRAFFIC_LIGHT
void TRAFFIC_LIGHT(PROC* p);

// asm:  .globl TRANSCHOICE
void TRANSCHOICE(void);

// asm:  .globl DIAL_ROUT
void DIAL_ROUT(void);

// asm:  .globl SHOW_CAR_STATISTICS
void SHOW_CAR_STATISTICS(void);

// asm:  .globl ROUNDER
void ROUNDER(void);

// asm:  .globl GETTHECARS
void GETTHECARS(void);

// asm:  .globl ULTRA_LOGO
void ULTRA_LOGO(void);

// asm:  .globl THE_CAR_CHOICE_PROC
void THE_CAR_CHOICE_PROC(void);

// leg.asm
// asm:  .globl LEG_INIT
void LEG_INIT(void);

// asm:  .globl LEG_GENERATE_MAP
void LEG_GENERATE_MAP(int start_index /*AR0*/, int end_index /*AR1*/);

// line.c
// asm:  .globl _rectangle,_line
void _rectangle(int x1, int y1, int x2, int y2, int color);

void _line(int x0, int y0, int x1, int y1, int color);

// math.asm
// asm:  .globl GEN_NORMAL
void GEN_NORMAL(VECTOR** points /*AR2*/, VECTOR* normal /*AR0*/);

// asm:  .globl _SINE,_COSI
c3x_reg_t _COSI(c3x_reg_t theta /*R2*/);
c3x_reg_t _SINE(c3x_reg_t theta /*R2*/);

// asm:  .globl ARCTANF
c3x_reg_t ARCTANF(c3x_reg_t x /*R2*/, c3x_reg_t y /*R3*/);

// asm:  .globl FIND_MATRIX
void FIND_MATRIX(void* dest /*AR2*/, VECTOR* radians /*R2*/);

// asm:  .globl INITMAT
void INITMAT(MATRIX* mat /*AR0*/);

// asm:  .globl FIND_XMATRIX,FIND_YMATRIX,FIND_ZMATRIX
void FIND_XMATRIX(void* dest /*AR2*/, c3x_reg_t radians /*R2*/);

void FIND_ZMATRIX(void* dest /*AR2*/, c3x_reg_t radians /*R2*/);

// asm:  .globl _find_Ymatrix
void _find_Ymatrix(void* dest /*AR2*/, c3x_reg_t radians /*R2*/);

// asm:  .globl HPFIND_YMATRIX
void HPFIND_YMATRIX(void* dest /*AR2*/, c3x_reg_t radians /*R2*/);

// asm:  .globl NORMAT,NORMALIZE
void NORMAT(void);

void NORMALIZE(VECTOR* vector /*AR2*/);

// asm:  .globl NORMIT,NORMITS
c3x_reg_t NORMIT(c3x_reg_t radians /*R2*/);

c3x_reg_t NORMITS(c3x_reg_t radians /*R2*/);

// asm:  .globl MATRIX_MUL
void MATRIX_MUL(VECTOR* src /*AR2*/, MATRIX* m3x3 /*R2*/, VECTOR* dst /*R3*/);

// asm:  .globl CONCAT201
void CONCAT201(MATRIX* s2 /*AR0*/, MATRIX* s1 /*AR2*/, MATRIX* d /*AR1*/);

// asm:  .globl CONCATMATV,CONCATMAT
void CONCATMATV(MATRIX* s1 /*AR2*/, MATRIX* s2 /*R2*/, MATRIX* d /*R3*/);

void CONCATMAT(MATRIX* s1 /*AR2*/, MATRIX* s2 /*R2*/, MATRIX* d /*R3*/);

// asm:  .globl VECTLEN,DOT,CPYMAT,CPYIMAT
void VECTLEN(void);

void CPYMAT(MATRIX* dst /*AR2*/, MATRIX* src /*R2*/);

void CPYIMAT(OBJ_MATRIX* dst /*AR2*/, MATRIX* src /*R2*/);

// asm:  .globl GETTHETADIFF
void GETTHETADIFF(void);

// asm:  .globl DIST_PT2LINE,GETLINE_EQ_2D
c3x_reg_t DIST_PT2LINE(LINE2D* line /*AR0*/, VECTOR* point /*AR1*/);

LINE2D* GETLINE_EQ_2D(VECTOR* p1 /*AR0*/, VECTOR* p2 /*AR1*/, LINE2D* line /*AR2*/);

// asm:  .globl CLR_VECTORA
void CLR_VECTORA(void);

// asm:  .globl SCALE_MATRIX
void SCALE_MATRIX(void);

// asm:  .globl FOLDMAP,UNFOLDMAP
void FOLDMAP(void);

void UNFOLDMAP(void);

// asm:  .globl TIME2STR
void TIME2STR(void);

// asm:  .globl CVTTIME
void CVTTIME(int time_code /*R0*/, int* hundredths /*R0*/, int* seconds /*R1*/, int* minutes /*R2*/);

// asm:  .globl UNFOLDMAP_NOPAL
void UNFOLDMAP_NOPAL(void);

// asm:  .globl RADAR_PLOT
void RADAR_PLOT(void);

// memtest.asm
// asm:  .globl TEST_CHIPS
void TEST_CHIPS(void);

// asm:  .globl TEST_STATIC_CHIPS
void TEST_STATIC_CHIPS(void);

// motion.asm
// asm:  .globl INITIALIZATION_MOTION_CHECK
void INITIALIZATION_MOTION_CHECK(void);

// asm:  .globl LATCH_ERROR
void LATCH_ERROR(void);

// asm:  .globl PLMOTION,INITIALIZE_GALIL
void PLMOTION(void);

// asm:  .globl LEVEL_THE_MOTION
void LEVEL_THE_MOTION(void);

// asm:  .globl MOTION_DLPROG
void MOTION_DLPROG(void);

// asm:  .globl RESET_GALIL
void RESET_GALIL(void);

// asm:  .globl CHECKPOINT_HIT_R
void CHECKPOINT_HIT_R(void);

// asm:  .globl SECTION_ROUTINE
void SECTION_ROUTINE(int routine_index /*AR0*/);

// asm:  .globl CHECKPOINT_HIT
void CHECKPOINT_HIT(void);

// asm:  .globl PLYR_CAR_INIT
void PLYR_CAR_INIT(void);

// asm:  .globl PLYR_INTRO_ENTER
void PLYR_INTRO_ENTER(void);

// asm:  .globl _PLYR,DRONEGO,GETSPD,OVELADD
void _PLYR(void);

void DRONEGO(OBJ* obj /*AR4*/, CARBLK* carblk /*AR5*/, c3x_reg_t steering_delta /*R2*/);

void GETSPD(OBJ* obj /*AR4*/, CARBLK* carblk /*AR5*/);

void OVELADD(OBJ* obj /*AR4*/);

// asm:  .globl GETCMOS_VALUES
void GETCMOS_VALUES(void);

// asm:  .globl GETTRAK
void GETTRAK(OBJ* obj /*AR4*/, CARBLK* carblk /*AR5*/);

// asm:  .globl CAMYADJ
void CAMYADJ(void);

// asm:  .globl _on_brake,_off_brake
void _on_brake(void);

void _off_brake(void);

// asm:  .globl _VIEW0,_VIEW1,_VIEW2,CAMVIEW
void _VIEW0(void);

void _VIEW1(void);

void _VIEW2(void);

void OVELNADD(void);

// asm:  .globl MKFXSND
void MKFXSND(void);

// asm:  .globl GETRDIR
c3x_reg_t GETRDIR(OBJ* track_obj /*AR2*/);

// asm:  .globl BONUS_WAIT_LOOP
void BONUS_WAIT_LOOP(void);

// asm:  .globl RACER_DRONE
void RACER_DRONE(PROC* p);

// asm:  .globl CARSCAN,OBSTABINIT,PLSCAN,GETRDOFFSET
void CARSCAN(OBJ* obj /*AR4*/, CARBLK* carblk /*AR5*/);

void OBSTABINIT(PROC* p /*AR7*/);

void PLSCAN(OBJ* obj /*AR4*/, CARBLK* carblk /*AR5*/);

c3x_reg_t GETRDOFFSET(PROC* p /*AR7*/, OBJ* obj /*AR4*/, CARBLK* carblk /*AR5*/);

// asm:  .globl DIFF_CHANGE,DIFF_TRICKLE
void DIFF_CHANGE(void);

// roadblck.asm
// asm:  .globl INIT_RDDEBRIS,ADD_RDDEBRIS,FREE_RDDEBRIS
void INIT_RDDEBRIS(void);

void ADD_RDDEBRIS(OBJ* obj /*AR4*/);

void FREE_RDDEBRIS(OBJ* obj /*AR2*/);

// asm:  .globl DEBRIS_SORT
void DEBRIS_SORT(void);

// roadkill.asm
// asm:  .globl ROADKILL_HIT,ROADKILL_FLYERP
void ROADKILL_HIT(void);

void ROADKILL_FLYERP(void);

// asm:  .globl ROADKILL_SETKILL
void ROADKILL_SETKILL(void);

// asm:  .globl GET_ROADKILL_TRACK,PROC_COUNT,OBJ_MOVE_GROUND
void GET_ROADKILL_TRACK(void);

void PROC_COUNT(void);

void OBJ_MOVE_GROUND(void);

// asm:  .globl DELETE_SPLAT,BUG_SPAWNER_PROC,PLYRROADKILL
void DELETE_SPLAT(void);

void BUG_SPAWNER_PROC(void);

void PLYRROADKILL(void);

// asm:  .globl DEER_SPAWNER_PROC,DEER_EXPLODE,FLYING_PARTS
void DEER_SPAWNER_PROC(void);

void DEER_EXPLODE(void);

void FLYING_PARTS(void);

// asm:  .globl GEESE_SPAWNER
void GEESE_SPAWNER(void);

// asm:  .globl COW_SPAWNER_PROC
void COW_SPAWNER_PROC(void);

// routs.asm
// asm:  .globl SQRT
c3x_reg_t SQRT(c3x_reg_t x /*R2*/);

c3x_reg_t DIV_F30(c3x_reg_t u, c3x_reg_t v);

void DIV_I30(void);

// asm:  .globl DIV_U30
void DIV_U30(void);

// asm:         .globl INV_F30
c3x_reg_t INV_F30(c3x_reg_t);

// asm:  .globl MOD_I30
void MOD_I30(void);

// asm:  .globl MOD_U30
void MOD_U30(void);

// rroad.asm
// asm:  .globl GETFLYMAT_TRAIN,FLYTRAINPI,FLYTRAIN
void GETFLYMAT_TRAIN(void);

void FLYTRAIN(void);

// asm:  .globl RRSTART_ENGINE,RRSTART_FLATBED,RRSTART_BOXCAR
void RRSTART_ENGINE(OBJ* obj /*AR4*/);

void RRSTART_BOXCAR(OBJ* obj /*AR4*/);

// asm:  .globl FLYCARP,CARSMASH,FLYTRAIN
void FLYCARP(void);

// asm:  .globl DEADCARA
void DEADCARA(void);

// asm:  .globl RAMPDOWNTRAINSND
void RAMPDOWNTRAINSND(void);

// asm:  .globl CLEANUP_PALS
void CLEANUP_PALS(void);

// smoke.asm
// asm:  .globl SMOKE_PROC,TIRE_SMOKE_COUNT
void SMOKE_PROC(void);

// asm:  .globl SORT_SMOKE
void SORT_SMOKE(void);

// snd.asm
// asm:  .globl SET_TUNE_LINKED
void SET_TUNE_LINKED(void);

// asm:  .globl PLYR_ENGINE
void PLYR_ENGINE(void);

// asm:  .globl ONESND,ONESNDFX
void ONESND(int sound_index);

void ONESNDFX(int sound_index);

// asm:  .globl SNDPROC
void SNDPROC(void);

// asm:  .globl CLRSNDDB
void CLRSNDDB(void);

// asm:  .globl SENDSND
void SENDSND(void);

// asm:  .globl SND_RESET_QUIET
void SND_RESET_QUIET(void);

// asm:  .globl RESET_SNDBRD
void RESET_SNDBRD(void);

// asm:  .globl SILENT
void SILENT(void);

// asm:  .globl SET_TUNE
void SET_TUNE(void);

// asm:  .globl RESUME_TUNE,LOOP_TUNE,TUNE_IDX,RESUME_TUNE_MK
void RESUME_TUNE(void);

// asm:  .globl SET_TRACK_VOL,SET_MASTER_VOL
void SET_MASTER_VOL(int volume);
void SET_TRACK_VOL(int track, int volume);

// asm:  .globl RESUME_TUNE_NT
void RESUME_TUNE_NT(void);

// asm:  .globl GETPRI
void GETPRI(void);

// asm:  .globl SET_STATION
void SET_STATION(void);

// asm:  .globl CHANGE_STATION
void CHANGE_STATION(void);

// asm:  .globl RADIO_BUT
void RADIO_BUT(void);

// asm:  .globl KILLSNDFX
void KILLSNDFX(void);

// asm:  .globl VOLSNDFX
void VOLSNDFX(int sound_index, int volume);

// spark.asm
// asm:  .globl SPARK_PROC,SPARK_COLLA_PROC,OBJ_MOVE,WALL_SPARK,IMPACT_SPARK
void SPARK_PROC(void);

void OBJ_MOVE(void);

void WALL_SPARK(void);

void IMPACT_SPARK(void);

// asm:  .globl SKID_SPARK,ROAD_IMPACT_SPARK,INIT_SPARK
void SKID_SPARK(void);

void ROAD_IMPACT_SPARK(void);

void INIT_SPARK(void);

// trans.asm
// asm:  .globl CHOOSE_TRANSMISSION
void CHOOSE_TRANSMISSION(void);

// asm:  .globl SIDE_DOOR,TILTWORLD
void SIDE_DOOR(void);

// asm:  .globl ZOOMTOCAR
void ZOOMTOCAR(void);

// asm:  .globl DROPTHECYCLE,DROPTHETURN
void DROPTHECYCLE(void);

void DROPTHETURN(void);

// asm:  .globl DROPTHEWHEEL,DROPTHEOTHER
void DROPTHEWHEEL(void);

void DROPTHEOTHER(void);

// asm:  .globl DOOR_OPENING
void DOOR_OPENING(void);

// asm:  .globl WHEEL_ROUT
void WHEEL_ROUT(void);

// asm:  .globl DOOR_ELEMENT_DELETE_ALL
void DOOR_ELEMENT_DELETE_ALL(void);

// asm:  .globl DOOR_ELEMENT_DELETE
void DOOR_ELEMENT_DELETE(void);

// asm:  .globl GET_UNIT_WHEEL
void GET_UNIT_WHEEL(void);

// asm:  .globl FIX_TRANSMISSION_SCREEN
void FIX_TRANSMISSION_SCREEN(void);

// asm:  .globl CYCLE_PUSH,TURNTO_SELECT
void CYCLE_PUSH(void);

void TURNTO_SELECT(void);

// asm:  .globl ADD_TO_DOOR_LIST
void ADD_TO_DOOR_LIST(void);

// asm:  .globl ENGINE_COLOR_INIT
void ENGINE_COLOR_INIT(void);

// asm:  .globl ENGINE_COLOR
void ENGINE_COLOR(void);

// asm:  .globl TRACK_SELECTION
void TRACK_SELECTION(void);

// asm:  .globl CLEANUP_TRACKSEL_PALS
void CLEANUP_TRACKSEL_PALS(void);

// totala.asm
// asm:  .globl BLTMOD2D_NOPAL
void BLTMOD2D_NOPAL(void);

// asm:  .globl _stuff_fpga
void _stuff_fpga(void);

// asm:  .globl _rdma
void _rdma(void);

// asm:  .globl BLTMOD2D
void BLTMOD2D(void);

// asm:  .globl BLTMOD2D_DS
void BLTMOD2D_DS(void);

// asm:  .globl SETPAGE0,SETPAGE1
void SETPAGE0(void);

void SETPAGE1(void);

void FASTCLR1(void);

// asm:  .globl CLRSCRN,CLRSCRN0,CLRSCRN1,SCREEN_FILL
void CLRSCRN(void);

void CLRSCRN0(void);

void CLRSCRN1(void);

word_addr_t SCREEN_FILL(word_addr_t start_addr, u32 color, u32 count_minus_one);

// asm:  .globl CLR255,CLR511,SCRNFIL
void CLR255(void);

void CLR511(void);

void SCRNFIL(void);

// asm:  .globl CLRCRAM
void CLRCRAM(void);

// asm:  .globl RANDOM,FRAND,SFRAND
uint32_t RANDOM(void);

c3x_reg_t FRAND(c3x_reg_t limit /*R0*/);

c3x_reg_t SFRAND(c3x_reg_t limit /*R0*/);

// asm:  .globl RANDU0,RANDU,SRAND,RANDPER
int RANDU0(int range /*AR2*/);

int RANDU(int range /*AR2*/);

int SRAND(int range /*AR2*/);

int RANDPER(int probability /*AR2*/);

// asm:  .globl INIT_LINKED_LIST
void INIT_LINKED_LIST(void* start_addr /*AR2*/, void** free_list /*R2*/, void** active_list /*R3*/, int length_minus_1 /*RC*/, int size /*RS*/);

// asm:  .globl GET_LLIST,ALLOC_LLIST
void* GET_LLIST(void** free_list, void** active_list);

void ALLOC_LLIST(void);

// asm:  .globl FREE_LLIST,DEL_LLIST
void FREE_LLIST(void);

void DEL_LLIST(void);

// asm:  .globl VEHICLE_ANI_INIT,CARPROC,LEAN
void VEHICLE_ANI_INIT(int vehicle_index /*AR2*/, OBJ* obj /*AR4*/);

void CARPROC(PROC* p);

void LEAN(PROC* p, DYNAOBJ* dyna, OBJ* obj, CARBLK* carblk);

// asm:  .globl DYNAOBJ_INIT,GETDYNA,DELDYNA
void DYNAOBJ_INIT(void);

DYNAOBJ* GETDYNA(void);

void DELDYNA(void);

// asm:  .globl CARB_INIT
void CARB_INIT(void);

// asm:  .globl GETCAR,DELCAR
CARBLK* GETCAR(void);

void DELCAR(void);

// asm:  .globl SCAN_OBJECTS
void SCAN_OBJECTS(PROC* p);

// asm:  .globl PUSHALL,POPALL
void PUSHALL(void);

void POPALL(void);

// asm:  .globl DISTANCE_2D
void DISTANCE_2D(void);

// asm:  .globl FORWARD
void FORWARD(VECTOR* src /*AR2*/, MATRIX* matrix /*R2*/, VECTOR* dst /*R3*/);

// asm:  .globl WAVE
void WAVE(int wave_index);

// asm:  .globl INIT_SYSTEM
void INIT_SYSTEM(void);

// asm:  .globl LOAD_FIXED_PALETTES
void LOAD_FIXED_PALETTES(void);

// asm:  .globl LOAD_STARTUP_PALS
void LOAD_STARTUP_PALS(void);

// asm:  .globl WAVEFLAG
void WAVEFLAG(PROC* p);

// asm:  .globl NUWHEEL,POSE
void NUWHEEL(void);

// asm:  .globl TOWHEEL
void TOWHEEL(void);

#endif /* GLOBALS_H */
