#ifndef H2HOBJ_H
#define H2HOBJ_H

/* Generated from asm/H2HOBJ.EQU. */

// OBJECTS.EQU
// 
// COPYRIGHT (C) 1994 TV GAMES, INC.
// ALL RIGHTS RESERVED
// 
// Generated by PComp v2.41
// 
// num_palettes	.set	3
// p1_p                	.set	0
// redhd1_p            	.set	1
// big2_p              	.set	2
// 
// num_objects	.set	7

// asm: h2p1                  	.set	0C1400Fh
#define h2p1 0x0C1400F

// asm: h2p1_I                	.set	03DF4h
#define h2p1_I 0x03DF4

// asm: h2p2                  	.set	0C1401Fh
#define h2p2 0x0C1401F

// asm: h2p2_I                	.set	03DF4h
#define h2p2_I 0x03DF4

// asm: h2p1a                 	.set	0C1402Fh
#define h2p1a 0x0C1402F

// asm: h2p1a_I               	.set	03DF4h
#define h2p1a_I 0x03DF4

// asm: h2p2b                 	.set	0C1403Fh
#define h2p2b 0x0C1403F

// asm: h2p2b_I               	.set	03DF4h
#define h2p2b_I 0x03DF4

// asm: redhd1              	.set	0C140D0h
#define redhd1 0x0C140D0

// asm: redhd1_I            	.set	03E1Eh
#define redhd1_I 0x03E1E

// asm: yelhd1              	.set	0C140E0h
#define yelhd1 0x0C140E0

// asm: yelhd1_I            	.set	03E1Eh
#define yelhd1_I 0x03E1E

// asm: big2                	.set	0C14171h
#define big2 0x0C14171

// asm: big2_I              	.set	03F5Bh
#define big2_I 0x03F5B

// num_sections	.set	1
// asm: head2head           	.set	0AF7D00h	;7940
#define head2head 0x0AF7D00 //7940

// .globl	head2head_PALETTES

// asm: H2HPAL1	.set	0C14000h
#define H2HPAL1 0x0C14000

// asm: H2HPAL2	.set	0C1404Eh
#define H2HPAL2 0x0C1404E

// asm: H2HPAL3	.set	0C140EFh
#define H2HPAL3 0x0C140EF

// asm: 	.globl	_SEChead2head
extern int _SEChead2head[2];

#endif /* H2HOBJ_H */
