
#include "heads.h"
#include "../core/machine.h"
#include "cmos.h"
#include "globals.h"
#include "macs.h"
#include "mproc.h"
#include "obj.h"
#include "objects.h"
#include "pall.h"
#include "sndtab.h"
#include "sys.h"
#include "sysid.h"
#include "text.h"
#include "vunit.h"

/*
 * Source module: asm/HEADS.ASM
 */

static void TEXTDELER(PROC* p);
static void VANITY_HEADS(PROC* p);
static void SET18FONTDS_WHITE(tSHADOW_TEXT* text);
void VANITY(PROC* p);
void VANITY_SUB(PROC* p);
static tSHADOW_TEXT GETT(const char* string, c3x_reg_t x, c3x_reg_t y);
static void CENTEREM(tSHADOW_TEXT* text);
static void RIGHTEM(tSHADOW_TEXT* text);
static void KRIS(PROC* p);
static void ADAMSTOPRIBYL(PROC* p);

#define HEADTYPE 0x88D0

// *----------------------------------------------------------------------------
static void TEXTDELER(PROC* p) {
    tTEXT** previous_link;
    tTEXT* text;

    switch (PROC_RESUME_STATE) {
    case 0:
        MAME_ASSERT_FUNCTION_ENTRY();
        break;
    case 1:
        goto PROC_RESUME_1;
    }

    // asm 0000A1A4: 	LDI	@TEXT_ACTIVEI,AR4
TEXTDELERLP:
    previous_link = &TEXT_ACTIVE;
    text = TEXT_ACTIVE;
    // asm 0000A1A5: 	LDI	*AR4,R0
    // asm 0000A1A6: 	BZ	TXTXX
    if (text == NULL) {
        goto TXTXX;
    }
TTEST:
    // asm 0000A1A7: LDI	R0,AR4
    // asm 0000A1A8: 	LDF	*+AR4(TEXT_POSY),R0
    // asm 0000A1A9: 	CMPF	-25,R0
    // asm 0000A1AA: 	BGT	TEXTDELERLP
    if (C3X_GT(C3X_LDF(text->posy), C3X_IMM_F32(-25))) {
        previous_link = &text->link;
        text = text->link;
        if (text == NULL) {
            goto TXTXX;
        }
        goto TTEST;
    }
    // asm 0000A1AB: 	LDI	*AR4,R7
    // asm 0000A1AC: 	LDI	@TEXT_ACTIVEI,R1	;get free list pointer
DELLP:
    // asm 0000A1AD: LDI	R1,AR1
    // asm 0000A1AE: 	LDI	*AR1,R1
#if DEBUG
    // asm: 	BZ	$			;lockup on end of list found
#endif
    // asm 0000A1AF: 	CMPI	R1,AR4
    // asm 0000A1B0: 	BNE	DELLP
    // asm 0000A1B1: 	LDI	*AR4,R1
    // asm 0000A1B2: 	STI	R1,*AR1			;LINK AROUND
    *previous_link = text->link;
    // asm 0000A1B3: 	LDI	@TEXT_FREE_COUNT,R1
    // asm 0000A1B4: 	INC	R1
    // asm 0000A1B5: 	STI	R1,@TEXT_FREE_COUNT
    TEXT_FREE_COUNT += 1;
    // asm 0000A1B6: 	LDI	@TEXT_FREEI,AR1		;get free list pointer
    // asm 0000A1B7: 	LDI	*AR1,R1
    // asm 0000A1B8: 	STI	R1,*AR4
    // asm 0000A1B9: 	STI	AR4,*AR1
    text->link = TEXT_FREE;
    TEXT_FREE = text;
    // asm 0000A1BA: 	LDI	R7,R0
    // asm 0000A1BB: 	BZ	TXTXX
    // asm 0000A1BC: 	BU	TTEST
    text = *previous_link;
    if (text != NULL) {
        goto TTEST;
    }
TXTXX:
    // asm 0000A1BD: 	SLEEP	1
    SLEEP(1, 1);
    // asm 0000A1BF: 	BU	TEXTDELER
    goto TEXTDELERLP;
}

// *----------------------------------------------------------------------------

/* asm: HEADS	.word	jeno */
/* asm: 	.word	marc */
/* asm: 	.word	pet */
/* asm: 	.word	xion */
/* asm: 	.word	ted */
/* asm: 	.word	matt */
/* asm: 	.word	vince */
/* asm: 	.word	carl */
/* asm: 	.word	glen */
/* asm: 	.word	ken */
/* asm: 	.word	eric */
/* asm: 	.word	-1 */
/* asm: 	 */
static int HEADS[] = {
    jeno_ROM,
    marc_ROM,
    pet_ROM,
    xion_ROM,
    ted_ROM,
    matt_ROM,
    vince_ROM,
    carl_ROM,
    glen_ROM,
    ken_ROM,
    eric_ROM,
    -1,
};

typedef struct VANITY_TEXT_ENTRY {
    int count;
    int x1;
    const char* text1;
    int x2;
    const char* text2;
    HEADS_FONT_FUNC font;
} VANITY_TEXT_ENTRY;

#define FMT_0() { .count = 0 }
#define FMT_1(S1) { .count = 1, .x1 = 256, .text1 = (S1) }
#define FMT_2(S1, S2) { .count = 2, .x1 = 50, .text1 = (S1), .x2 = 450, .text2 = (S2) }
#define FMT_3(S1) { .count = 3, .x1 = 256, .text1 = (S1) }
#define FMT_7(S1) { .count = 7, .x1 = 450, .text1 = (S1) }
#define FMT_8(S1) { .count = 8, .x1 = 50, .text1 = (S1) }
#define FMT_9(S1, S2) { .count = 9, .x1 = 50, .text1 = (S1), .x2 = 450, .text2 = (S2) }
#define FMT_10(S1) { .count = 10, .font = (S1) }
#define FMT_99(S1) { .count = 99, .x1 = 256, .text1 = (S1) }
#define FMT(CASE, ...) FMT_##CASE(__VA_ARGS__),
#define WORD(VALUE) { .count = (VALUE) },

/* asm: THANKS_TABLE (generated by asm/VANTAB.INC) */
static const VANITY_TEXT_ENTRY THANKS_TABLE[] = {
    FMT(1, "CRUISN USA")
    FMT(0)
    FMT(1, "DESIGN TEAM")
    FMT(0)
    FMT(2, "DIRECTOR", "EUGENE JARVIS")
    FMT(0)
    FMT(2, "SOFTWARE", "ERIC L PRIBYL")
    FMT(0)
    FMT(2, "HARDWARE DESIGN", "MARK LOFFREDO")
    FMT(7, "GLENN SHIPP")
    FMT(0)
    FMT(2, "3D-GRAPHICS", "XION COOPER")
    FMT(7, "TED BARBER")
    FMT(0)
    FMT(0)
    FMT(0)
    WORD(4)
    FMT(2, "MUSIC", "VINCE PONTARELLI")
    FMT(2, "SOUND FX", "MATT BOOTY")
    FMT(0)
    FMT(2, "ADDITIONAL CODE", "CARL MEY")
    FMT(0)
    FMT(2, "CABINET ART", "JOHN YOUSSI")
    FMT(7, "LINDA DEAL")
    FMT(7, "NIK EHRLICH")
    FMT(7, "GREG FRERES")
    FMT(0)
    FMT(2, "ADDITIONAL ART", "JOHN WATSON")
    FMT(7, "ANA VITEK")
    FMT(0)
    FMT(8, "MECHANICAL DESIGN AND MOTION")
    FMT(7, "TED VALAVANIS")
    FMT(7, "MATT DAVIS")
    FMT(7, "JIM KROL")
    FMT(7, "TOM SEDOR")
    FMT(7, "RAY CZAJKA")
    FMT(0)
    FMT(0)
    WORD(4)
    FMT(10, SETFIXEDFONTDS)
    FMT(2, "SOUND SYSTEM", "ED KEENAN")
    FMT(2, "DCS GURU", "RICH KARSTENS")
    FMT(0)
    FMT(2, "HARDWARE", "KEN WILLIAMS")
    FMT(7, "SHERIDAN OURSLER")
    FMT(7, "PAT COX")
    FMT(7, "AL LASKO")
    FMT(0)
    FMT(2, "PCB DESIGN", "STEVE NORRIS")
    FMT(7, "RAY GAY")
    FMT(0)
    FMT(2, "STARTING GIRL", "KATHRYN GARRISON")
    FMT(2, "TROPHY GIRL", "ANUTZA HERLING")
    FMT(2, "BEEFCAKE BOY", "SAL DIVITA")
    FMT(2, "RACE ANOUNCER", "GINGI LAHERA")
    FMT(2, "CRUISN VOCALS", "JEFF MORROW")
    FMT(2, "PREZ VOICE", "PAUL HEITSCH")
    FMT(2, "SATURATION AGENT WALKER", "JOHN COLT")
    FMT(2, "HOT TUB BABE", "MICHAEL LYNN FULLER")
    FMT(0)
    FMT(2, "ART TOOLS", "ERIC L PRIBYL")
    FMT(7, "WARREN DAVIS")
    FMT(0)
    FMT(2, "SOFTWARE TOOLS", "ERIC L PRIBYL")
    FMT(7, "TODD ALLEN")
    FMT(7, "EDWIN REICH")
    FMT(0)
    FMT(2, "MANAGEMENT", "PAUL DUSSAULT")
    FMT(7, "CARY MEDNICK")
    FMT(7, "WALLY SMOLUCHA")
    FMT(0)
    FMT(2, "COMMUNICATIONS", "MONIQUE JAGIELNIK")
    FMT(7, "CECILIA ROCKETT")
    FMT(7, "DARLENE CRAWFORD")
    FMT(7, "KATHY KLINE")
    FMT(0)
    FMT(2, "PROMOTIONAL VIDEOS", "JIM GREENE")
    FMT(7, "ART TIANIS")
    FMT(7, "JOAN FAUX")
    FMT(7, "TAL LEKBERG")
    FMT(0)
    FMT(2, "SALES AND MARKETING", "JOE DILLON")
    FMT(7, "ROGER SHARPE")
    FMT(7, "BARB ROSENTHAL")
    FMT(7, "MICHAL LYNN FULLER")
    FMT(7, "CHRISTA WOSS")
    FMT(7, "LENORE SAYERS")
    FMT(7, "RACHEL DAVIS")
    FMT(7, "BOB LENTZ")
    FMT(0)
    FMT(2, "FERRETS", "KATO")
    FMT(7, "SOPHI")
    FMT(7, "GEORGE BERNSTIEN")
    FMT(7, "TANZI")
    FMT(7, "GIZMO")
    FMT(0)
    FMT(8, "EXECUTIVE PRODUCERS")
    FMT(7, "MR ARAKAWA")
    FMT(7, "HOWARD LINCOLN")
    FMT(7, "NEIL NICASTRO")
    FMT(7, "KEN FEDESNA")
    FMT(7, "JOEL HOCHBERG")
    FMT(7, "KEN LOBB")
    FMT(7, "DON JAMES")
    FMT(0)
    FMT(2, "ASSISTANT", "DEBBIE SILKWOOD")
    FMT(8, "PRODUCER")
    FMT(0)
    FMT(2, "TEST", "MIKE GOTTLIEB")
    FMT(7, "DARREN WALKER")
    FMT(0)
    FMT(2, "LEGAL", "NATE DARDICK")
    FMT(7, "BARBARA NORMAN")
    FMT(7, "KATIE CZERWINSKI")
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(1, "SPECIAL THANKS")
    FMT(0)
    FMT(1, "STEVE RITCHIE")
    FMT(1, "PAUL HEITSCH")
    FMT(1, "PAT LAWLOR")
    FMT(1, "LARRY DEMAR")
    FMT(1, "JAKE SIMPSON")
    FMT(1, "WENDY JEWART")
    FMT(1, "GEORGE PETRO")
    FMT(1, "JORGE GOMEZ")
    FMT(1, "ED BOON")
    FMT(1, "JACK HAEGAR")
    FMT(1, "JOHN TOBIAS")
    FMT(1, "MARK TURMELL")
    FMT(0)
    FMT(1, "AND EVERYONE AT NINTENDO MIDWAY AND TV GAMES")
    FMT(0)
    FMT(1, "NO ANIMALS WERE HARMED DURING DEVELOPMENT")
    FMT(1, "OF THIS GAME")
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(1, "VERY SPECIAL THANKS TO")
    FMT(0)
    FMT(3, "CHRISTINE ADAMS")
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(1, "JERI ALI MIKEY")
    FMT(0)
    FMT(99, "AND KRISTIAN")
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(0)
    FMT(1, "COPYRIGHT 1994 NINTENDO")
    FMT(1, "DEVELOPED BY TV GAMES INC")
    FMT(1, "MANUFACTURED AND SOLD BY MIDWAY")
    FMT(1, "MANUFACTURING COMPANY UNDER LICENSE")
    FMT(0)
    WORD(4)
    WORD(4)
    WORD(-1)
};

#undef WORD
#undef FMT
#undef FMT_99
#undef FMT_10
#undef FMT_9
#undef FMT_8
#undef FMT_7
#undef FMT_3
#undef FMT_2
#undef FMT_1
#undef FMT_0

/*
 *----------------------------------------------------------------------------
 *
 *
 *
 */
static void VANITY_HEADS(PROC* p) {
    const int* head;
    OBJ* obj;
    c3x_reg_t angle;

    switch (PROC_RESUME_STATE) {
    case 0:
        MAME_ASSERT_FUNCTION_ENTRY();
        break;
    case 1:
        goto PROC_RESUME_1;
    }

    // asm 0000A1CC: 	SETDP
    // asm 0000A1CD: 	LDI	@CAMERAPOSI,AR6
    // asm 0000A1CE: 	CLRF	R0
    // asm 0000A1CF: 	STF	R0,*+AR6(X)
    // asm 0000A1D0: 	STF	R0,*+AR6(Y)
    // asm 0000A1D1: 	STF	R0,*+AR6(Z)
    _CAMERAPOS.X = C3X_STF(C3X_FROM_INT(0));
    _CAMERAPOS.Y = C3X_STF(C3X_FROM_INT(0));
    _CAMERAPOS.Z = C3X_STF(C3X_FROM_INT(0));
    // asm 0000A1D2: 	LDL	theheads_PALETTES,AR2
    // asm 0000A1D3: 	CALL	alloc_section
    alloc_section(theheads_PALETTES);
    // asm 0000A1D4: 	FIFO_CLRP	R0		;IS THE FIFO CLEAR
    // asm 0000A1D9: 	DMA_WT		R0
    // asm 0000A1DE: 	CALL	FIFO_RESET
    FIFO_RESET();
    // asm 0000A1DF: 	LDI	1,R0
    // asm 0000A1E0: 	STI	R0,@HARD_SECTION_LOAD
    HARD_SECTION_LOAD = 1;
    // asm 0000A1E1: 	LDL	_SECtheheads,AR2
    // asm 0000A1E2: 	CALL	LOAD_SECTION_REQ
    LOAD_SECTION_REQ(&SECtheheads_HEADS);
    // asm 0000A1E3: 	LDL	HEADS,AR5
    head = HEADS;
    // ;	CLRF	R6
    // asm 0000A1E4: 	LDF	PI,R6
    angle = C3X_IMM_F32(PI);
VANHDLP:
    // asm 0000A1E5: 	LDI	*AR5++,R0
    // asm 0000A1E6: 	BN	VHIX
    if (*head < 0) {
        goto VHIX;
    }
    // asm 0000A1E7: 	LDI	R0,AR2
    // asm 0000A1E8: 	CALL	OBJ_GETE
    obj = OBJ_GETE(ROM_PTR(*head++));
    // asm 0000A1E9: 	LDF	R6,R2
    // ;	CALL	_SINE
    // asm 0000A1EA: 	PUSH	AR0
    // asm 0000A1EB: 	CALL	_HPsin
    // asm 0000A1EC: 	POP	AR0
    // asm 0000A1ED: 	MPYF	130,R0
    // asm 0000A1EE: 	STF	R0,*+AR0(OPOSX)
    obj->pos.X = C3X_STF(C3X_MUL(_HPsin(angle), C3X_IMM_F32(130)));
    // asm 0000A1EF: 	LDF	R6,R2
    // ;	CALL	_COSI
    // asm 0000A1F0: 	PUSH	AR0
    // asm 0000A1F1: 	CALL	_HPcos
    // asm 0000A1F2: 	POP	AR0
    // asm 0000A1F3: 	MPYF	130,R0
    // asm 0000A1F4: 	STF	R0,*+AR0(OPOSY)
    obj->pos.Y = C3X_STF(C3X_MUL(_HPcos(angle), C3X_IMM_F32(130)));
    // asm 0000A1F5: 	FLOAT	368,R0
    // asm 0000A1F6: 	STF	R0,*+AR0(OPOSZ)
    obj->pos.Z = C3X_STF(C3X_FROM_INT(368));
    // asm 0000A1F7: 	STF	R6,*+AR0(ORADY)
    obj->rady = C3X_STF(angle);
    // asm 0000A1F8: 	LDI	AR0,AR2
    // asm 0000A1F9: 	CALL	OBJ_INSERT
    OBJ_INSERT(obj);
    // asm 0000A1FA: 	SUBF	0.571,R6
    angle = C3X_SUB(angle, C3X_IMM_F32(0.571));
    // asm 0000A1FB: 	B	VANHDLP
    goto VANHDLP;
VHIX:
    // ;	DIE
VANITY_HEADS_LP:
    // asm 0000A1FC: 	LDI	@OACTIVEI,AR0
    obj = OACTIVE;
VOLP:
    // asm 0000A1FD: 	LDI	*AR0,R0
    // asm 0000A1FE: 	BZ	VOSLP
    if (obj == NULL) {
        goto VOSLP;
    }
    // asm 0000A1FF: 	LDI	R0,AR0
    // asm 0000A200: 	LDF	*+AR0(ORADY),R2
    // asm 0000A201: 	ADDF	0.01,R2
    // asm 0000A202: 	STF	R2,*+AR0(ORADY)
    angle = C3X_ADD(C3X_LDF(obj->rady), C3X_IMM_F32(0.01));
    obj->rady = C3X_STF(angle);
    // asm 0000A203: 	LDF	R2,R6
    // asm 0000A204: 	CALL	_SINE
    // asm 0000A205: 	MPYF	130,R0
    // asm 0000A206: 	STF	R0,*+AR0(OPOSX)
    obj->pos.X = C3X_STF(C3X_MUL(_SINE(angle), C3X_IMM_F32(130)));
    // asm 0000A207: 	LDF	R6,R2
    // asm 0000A208: 	CALL	_COSI
    // asm 0000A209: 	MPYF	130,R0
    // asm 0000A20A: 	STF	R0,*+AR0(OPOSY)
    obj->pos.Y = C3X_STF(C3X_MUL(_COSI(angle), C3X_IMM_F32(130)));
    // asm 0000A20B: 	BU	VOLP
    obj = obj->link;
    goto VOLP;
VOSLP:
    // asm 0000A20C: SLEEP	1
    SLEEP(1, 1);
    // asm 0000A20E: 	BU	VANITY_HEADS_LP
    goto VANITY_HEADS_LP;
}

// *----------------------------------------------------------------------------

// *----------------------------------------------------------------------------
static void SET18FONTDS_WHITE(tSHADOW_TEXT* text) {
    int palette;

    // asm 0000A20F: 	CALL	SET18FONTDS
    SET18FONTDS(text);
    // asm 0000A210: 	LDL	font18_white,AR2
    // asm 0000A211: 	CALL	PAL_FIND_RAW
    palette = PAL_FIND_RAW((tPAL*)ROM_PTR(font18_white_ROM));
    // asm 0000A212: 	STI	R0,*+AR0(TEXT_PAL)
    // asm 0000A213: 	STI	R0,*+AR1(TEXT_PAL)
    text->front->palette = palette;
    text->shadow->palette = palette;
    // asm 0000A214: 	RETS
}

// *----------------------------------------------------------------------------

/* asm: YINCREMENT	.bss	YINCREMENT,1 */
c3x_f32_t YINCREMENT;

void VANITY(PROC* p) {
    switch (PROC_RESUME_STATE) {
    case 0:
        MAME_ASSERT_FUNCTION_ENTRY();
        break;
    case 1:
        goto PROC_RESUME_1;
    }

    // asm 0000A215: 	JSRP	VANITY_SUB
    JSRP(VANITY_SUB, 1);
    // asm 0000A21B: 	BR	CYCLE_ATTR
    CYCLE_ATTR();
    return;
}

void VANITY_SUB(PROC* p) {
    const VANITY_TEXT_ENTRY* entry;
    tSHADOW_TEXT text;
    PROC_CONTEXT* child_ctx;

    switch (PROC_RESUME_STATE) {
    case 0:
        MAME_ASSERT_FUNCTION_ENTRY();
        MAME_ASSERT_ORDERING("VANITY_SUB");
        break;
    case 1:
        goto PROC_RESUME_1;
    case 2:
        goto PROC_RESUME_2;
    case 3:
        goto PROC_RESUME_3;
    }

    // asm 0000A21C: 	LDI	MATTR,R0
    // asm 0000A21D: 	STI	R0,@_MODE
    _MODE = MATTR;
    // asm 0000A21E: 	LDI	1,R0
    // asm 0000A21F: 	STI	R0,@COINOFF
    COINOFF = 1;
    // asm 0000A220: 	CLRI	R0
    // asm 0000A221: 	STI	R0,@BGNDCOLA
    BGNDCOLA = 0;
    // asm 0000A222: 	STI	R0,@NOAERASE
    NOAERASE = 0;
    // asm 0000A223: 	LDI	@CAMERAPOSI,AR6
    // asm 0000A224: 	CLRF	R2
    // asm 0000A225: 	STF	R2,*+AR6(X)
    // asm 0000A226: 	STF	R2,*+AR6(Y)
    // asm 0000A227: 	STF	R2,*+AR6(Z)
    _CAMERAPOS.X = C3X_STF(C3X_FROM_INT(0));
    _CAMERAPOS.Y = C3X_STF(C3X_FROM_INT(0));
    _CAMERAPOS.Z = C3X_STF(C3X_FROM_INT(0));
    // asm 0000A228: 	LDI	@CAMERARADI,AR6
    // asm 0000A229: 	STF	R2,*+AR6(X)
    // asm 0000A22A: 	STF	R2,*+AR6(Y)
    // asm 0000A22B: 	STF	R2,*+AR6(Z)
    _CAMERARAD.X = C3X_STF(C3X_FROM_INT(0));
    _CAMERARAD.Y = C3X_STF(C3X_FROM_INT(0));
    _CAMERARAD.Z = C3X_STF(C3X_FROM_INT(0));
    // asm 0000A22C: 	LDI	@CAMERAMATRIXI,AR2
    // asm 0000A22D: 	CALL	FIND_YMATRIX
    FIND_YMATRIX(&_CAMERAMATRIX, C3X_FROM_INT(0));
    // asm 0000A22E: 	SLEEP	1
    SLEEP(1, 1);
    // asm 0000A230: 	CREATE	VANITY_HEADS,HEADTYPE
    child_ctx = NEW_PROC_CONTEXT();
    CREATE(VANITY_HEADS, HEADTYPE, child_ctx);
    // asm 0000A233: 	CREATE	TEXTDELER,HEADTYPE
    child_ctx = NEW_PROC_CONTEXT();
    CREATE(TEXTDELER, HEADTYPE, child_ctx);
    // ;	CREATE	LOGO_WATCH,UTIL_C
    // asm 0000A236: 	LDL	SET18FONTDS_WHITE,R0
    // asm 0000A237: 	STI	R0,@FONTUSED
    FONTUSED = SET18FONTDS_WHITE;
    // asm 0000A238: 	LDF	24,R0
    // asm 0000A239: 	STF	R0,@YINCREMENT
    YINCREMENT = C3X_STF(C3X_IMM_F32(24));
    // asm 0000A23A: 	FLOAT	420,R6
    p->ctx.VANITY_SUB.y = C3X_FROM_INT(420);
    // asm 0000A23B: 	LDI	2,AR5
    // asm 0000A23C: 	LDI	@THANKS_TABLEI,AR4
    p->ctx.VANITY_SUB.table_index = 0;
DTLP2:
    // asm 0000A23D: 	ADDF	@YINCREMENT,R6		;ADDF	24,R6
    p->ctx.VANITY_SUB.y = C3X_ADD(p->ctx.VANITY_SUB.y, C3X_LDF(YINCREMENT));
KKPD:
    // asm 0000A23E: FLOAT	402,R0
    // asm 0000A23F: 	CMPF	R0,R6
    // asm 0000A240: 	BLT	JJDDA
    if (C3X_LT(p->ctx.VANITY_SUB.y, C3X_FROM_INT(402))) {
        goto JJDDA;
    }
    // asm 0000A241: 	SLEEP	1
    SLEEP(1, 2);
    // asm 0000A243: 	SUBF	1,R6
    p->ctx.VANITY_SUB.y = C3X_SUB(p->ctx.VANITY_SUB.y, C3X_IMM_F32(1));
    // asm 0000A244: 	BU	KKPD
    goto KKPD;
JJDDA:
    // asm 0000A245: 	LDI	*AR4++,R7	;number of entries
    entry = &THANKS_TABLE[p->ctx.VANITY_SUB.table_index++];
    // asm 0000A246: 	CMPI	10,R7
    // asm 0000A247: 	BNE	NOT10
    if (entry->count != 10) {
        goto NOT10;
    }
    // asm 0000A248: 	LDI	*AR4++,R0
    // asm 0000A249: 	STI	R0,@FONTUSED
    FONTUSED = entry->font;
    // asm 0000A24A: 	LDF	10,R0
    // asm 0000A24B: 	STF	R0,@YINCREMENT
    YINCREMENT = C3X_STF(C3X_IMM_F32(10));
    // asm 0000A24C: 	BU	KKPD
    goto KKPD;
NOT10:
    // asm 0000A24D: 	CMPI	8,R7
    // asm 0000A24E: 	BNE	NOTSPEC8
    if (entry->count != 8) {
        goto NOTSPEC8;
    }
    // asm 0000A24F: 	FLOAT	*AR4++,R2
    // asm 0000A250: 	LDF	R6,R3
    // asm 0000A251: 	LDI	*AR4++,AR2
    // asm 0000A252: 	CALL	GETT
    GETT(entry->text1, C3X_FROM_INT(entry->x1), p->ctx.VANITY_SUB.y);
    // asm 0000A253: 	BU	DTLP2
    goto DTLP2;
NOTSPEC8:
    // asm 0000A254: 	CMPI	7,R7
    // asm 0000A255: 	BNE	NOTSPEC7
    if (entry->count != 7) {
        goto NOTSPEC7;
    }
    // asm 0000A256: 	FLOAT	*AR4++,R2
    // asm 0000A257: 	LDF	R6,R3
    // asm 0000A258: 	LDI	*AR4++,AR2
    // asm 0000A259: 	CALL	GETT
    text = GETT(entry->text1, C3X_FROM_INT(entry->x1), p->ctx.VANITY_SUB.y);
    // asm 0000A25A: 	CALL	RIGHTEM
    RIGHTEM(&text);
    // asm 0000A25B: 	BU	DTLP2
    goto DTLP2;
NOTSPEC7:
    // asm 0000A25C: 	CMPI	4,R7
    // asm 0000A25D: 	BNE	NOTSPEC4
    if (entry->count != 4) {
        goto NOTSPEC4;
    }
    // asm 0000A25E: 	LDI	1,R0
    // asm 0000A25F: 	STI	R0,@TEXT_FREEZE
    TEXT_FREEZE = 1;
    // asm 0000A260: 	SLEEP	60
    SLEEP(60, 3);
    // asm 0000A262: 	CLRI	R0
    // asm 0000A263: 	STI	R0,@TEXT_FREEZE
    TEXT_FREEZE = 0;
    // asm 0000A264: 	BU	KKPD
    goto KKPD;
NOTSPEC4:
    // asm 0000A265: 	CMPI	99,R7
    // asm 0000A266: 	BNE	NOTSPEC99
    if (entry->count != 99) {
        goto NOTSPEC99;
    }
    // asm 0000A267: 	FLOAT	*AR4++,R2
    // asm 0000A268: 	FLOAT	(256-600),R2
    // asm 0000A269: 	LDF	R6,R3
    // asm 0000A26A: 	LDI	*AR4++,AR2
    // asm 0000A26B: 	CALL	GETT
    text = GETT(entry->text1, C3X_FROM_INT(256 - 600), p->ctx.VANITY_SUB.y);
    // asm 0000A26C: 	CALL	CENTEREM
    CENTEREM(&text);
    // asm 0000A26D: 	PUSH	AR4
    // asm 0000A26E: 	PUSH	AR5
    // asm 0000A26F: 	LDI	AR0,AR4
    // asm 0000A270: 	LDI	AR1,AR5
    // asm 0000A271: 	CREATE	KRIS,HEADTYPE
    child_ctx = NEW_PROC_CONTEXT();
    child_ctx->KRIS.front = text.front;
    child_ctx->KRIS.shadow = text.shadow;
    CREATE(KRIS, HEADTYPE, child_ctx);
    // asm 0000A274: 	POP	AR5
    // asm 0000A275: 	POP	AR4
    // asm 0000A276: 	BU	DTLP2
    goto DTLP2;
NOTSPEC99:
    // asm 0000A286: 	CMPI	3,R7
    // asm 0000A287: 	BNE	NOTSPEC3
    if (entry->count != 3) {
        goto NOTSPEC3;
    }
    // asm 0000A288: 	FLOAT	*AR4++,R2
    // asm 0000A289: 	LDF	R6,R3
    // asm 0000A28A: 	LDI	*AR4++,AR2
    // asm 0000A28B: 	CALL	GETT
    text = GETT(entry->text1, C3X_FROM_INT(entry->x1), p->ctx.VANITY_SUB.y);
    // asm 0000A28C: 	CALL	CENTEREM
    CENTEREM(&text);
    // asm 0000A28D: 	PUSH	AR4
    // asm 0000A28E: 	PUSH	AR5
    // asm 0000A28F: 	LDI	AR0,AR4
    // asm 0000A290: 	LDI	AR1,AR5
    // asm 0000A291: 	CREATE	ADAMSTOPRIBYL,HEADTYPE
    child_ctx = NEW_PROC_CONTEXT();
    child_ctx->ADAMSTOPRIBYL.front = text.front;
    child_ctx->ADAMSTOPRIBYL.shadow = text.shadow;
    CREATE(ADAMSTOPRIBYL, HEADTYPE, child_ctx);
    // asm 0000A294: 	POP	AR5
    // asm 0000A295: 	POP	AR4
    // asm 0000A296: 	BU	DTLP2
    goto DTLP2;
NOTSPEC3:
    // asm 0000A2A2: 	CMPI	-1,R7
    // asm 0000A2A3: 	BEQ	WTD55
    if (entry->count == -1) {
        goto WTD55;
    }
    // asm 0000A2A4: 	CMPI	0,R7
    // asm 0000A2A5: 	BNE	NOT0
    if (entry->count != 0) {
        goto NOT0;
    }
    // asm 0000A2A6: 	BU	DTLP2
    goto DTLP2;
NOT0:
    // asm 0000A2A7: 	CMPI	2,R7
    // asm 0000A2A8: 	BEQ	TWO
    if (entry->count == 2) {
        goto TWO;
    }
    // 	;ONE
    // asm 0000A2A9: 	FLOAT	*AR4++,R2
    // asm 0000A2AA: 	LDF	R6,R3
    // asm 0000A2AB: 	LDI	*AR4++,AR2
    // asm 0000A2AC: 	CALL	GETT
    text = GETT(entry->text1, C3X_FROM_INT(entry->x1), p->ctx.VANITY_SUB.y);
    // asm 0000A2AD: 	CALL	CENTEREM
    CENTEREM(&text);
    // asm 0000A2AE: 	BU	DTLP2
    goto DTLP2;
TWO:
    // asm 0000A2AF: 	FLOAT	*AR4++,R2
    // asm 0000A2B0: 	LDF	R6,R3
    // asm 0000A2B1: 	LDI	*AR4++,AR2
    // asm 0000A2B2: 	CALL	GETT
    GETT(entry->text1, C3X_FROM_INT(entry->x1), p->ctx.VANITY_SUB.y);
    // asm 0000A2B3: 	FLOAT	*AR4++,R2
    // asm 0000A2B4: 	LDF	R6,R3
    // asm 0000A2B5: 	LDI	*AR4++,AR2
    // asm 0000A2B6: 	CALL	GETT
    text = GETT(entry->text2, C3X_FROM_INT(entry->x2), p->ctx.VANITY_SUB.y);
    // asm 0000A2B7: 	CALL	RIGHTEM
    RIGHTEM(&text);
    // asm 0000A2B8: 	BU	DTLP2
    goto DTLP2;
WTD55:
    // asm 0000A2B9: 	LDI	HEADTYPE,R0
    // asm 0000A2BA: 	LDI	-1,R1
    // asm 0000A2BB: 	CALL	PRC_KILLALL
    PRC_KILLALL(HEADTYPE, -1);
    // asm 0000A2BC: 	RETP
    return;
}

static void KRIS(PROC* p) {
    c3x_reg_t position;
    c3x_reg_t delta;

    switch (PROC_RESUME_STATE) {
    case 0:
        MAME_ASSERT_FUNCTION_ENTRY();
        break;
    case 1:
        goto PROC_RESUME_1;
    }

KRIS_LOOP:
    // asm 0000A277: SLEEP	1
    SLEEP(1, 1);
    // asm 0000A279: 	LDF	*+AR4(TEXT_POSX),R0
    position = C3X_LDF(p->ctx.KRIS.front->posx);
    // asm 0000A27A: 	FLOAT	259,R1
    // asm 0000A27B: 	SUBF	R0,R1
    // asm 0000A27C: 	MPYF	0.05,R1
    // asm 0000A27D: 	ADDF	R1,R0
    delta = C3X_MUL(C3X_SUB(C3X_FROM_INT(259), position), C3X_IMM_F32(0.05));
    // asm 0000A27E: 	STF	R0,*+AR4(TEXT_POSX)
    p->ctx.KRIS.front->posx = C3X_STF(C3X_ADD(position, delta));
    // asm 0000A27F: 	LDF	*+AR5(TEXT_POSX),R0
    position = C3X_LDF(p->ctx.KRIS.shadow->posx);
    // asm 0000A280: 	FLOAT	256,R1
    // asm 0000A281: 	SUBF	R0,R1
    // asm 0000A282: 	MPYF	0.05,R1
    // asm 0000A283: 	ADDF	R1,R0
    delta = C3X_MUL(C3X_SUB(C3X_FROM_INT(256), position), C3X_IMM_F32(0.05));
    // asm 0000A284: 	STF	R0,*+AR5(TEXT_POSX)
    p->ctx.KRIS.shadow->posx = C3X_STF(C3X_ADD(position, delta));
    // asm 0000A285: 	BU	KRIS
    goto KRIS_LOOP;
}

/* asm: CHISPRIB SPTR "CHRISTINE PRIBYL" */
static const char CHISPRIB[] = "CHRISTINE PRIBYL";

static void ADAMSTOPRIBYL(PROC* p) {
    switch (PROC_RESUME_STATE) {
    case 0:
        MAME_ASSERT_FUNCTION_ENTRY();
        break;
    case 1:
        goto PROC_RESUME_1;
    }

ADAMSTOPRIBYL_LOOP:
    // asm 0000A298: 	SLEEP	1
    SLEEP(1, 1);
    // asm 0000A29A: 	LDF	*+AR4(TEXT_POSY),R0
    // asm 0000A29B: 	FLOAT	250,R1
    // asm 0000A29C: 	CMPF	R1,R0
    // asm 0000A29D: 	BGT	ADAMSTOPRIBYL
    if (C3X_GT(C3X_LDF(p->ctx.ADAMSTOPRIBYL.front->posy), C3X_FROM_INT(250))) {
        goto ADAMSTOPRIBYL_LOOP;
    }
    // asm 0000A29E: 	LDI	@CHISPRIB,R0
    // asm 0000A29F: 	STI	R0,*+AR4(TEXT_PTR)
    // asm 0000A2A0: 	STI	R0,*+AR5(TEXT_PTR)
    p->ctx.ADAMSTOPRIBYL.front->ptr = (char*)CHISPRIB;
    p->ctx.ADAMSTOPRIBYL.shadow->ptr = (char*)CHISPRIB;
    // asm 0000A2A1: 	DIE
    DIE();
}

// *----------------------------------------------------------------------------

/*
 *----------------------------------------------------------------------------
 *SUBROUTINE FOR THE ABOVE
 *
 *
 *PARAMETERS
 *	AR2	STRING
 *	R2	X
 *	R3	Y
 *	R4	FONT
 *RETURNS
 *	AR0	S1
 *	AR1	S2
 *
 */

/* asm: FONTUSED	.bss	FONTUSED,1 */
HEADS_FONT_FUNC FONTUSED;

/*
;	LDL	SET18FONTDS
;	LDL	SETFIXEDFONTDS
*/
static tSHADOW_TEXT GETT(const char* string, c3x_reg_t x, c3x_reg_t y) {
    tSHADOW_TEXT text;

    // asm 0000A2C0: 	LDI	9999,RC
    // asm 0000A2C1: 	CALL	TEXT_ADDDS
    text = TEXT_ADDDS(string, x, y, 9999);
    // asm 0000A2C2: 	LDF	-1,R0
    // asm 0000A2C3: 	STF	R0,*+AR0(TEXT_VELY)
    // asm 0000A2C4: 	STF	R0,*+AR1(TEXT_VELY)
    text.front->vely = C3X_STF(C3X_IMM_F32(-1));
    text.shadow->vely = C3X_STF(C3X_IMM_F32(-1));
    // asm 0000A2C5: 	LDI	@FONTUSED,R0
    // asm 0000A2C6: 	CALLU	R0
    FONTUSED(&text);
    // asm 0000A2C7: 	RETS
    return text;
}

static void CENTEREM(tSHADOW_TEXT* text) {
    // asm 0000A2C8: 	LDI	*+AR0(TEXT_COLOR),R0
    // asm 0000A2C9: 	OR	TXT_CENTER,R0
    // asm 0000A2CA: 	STI	R0,*+AR0(TEXT_COLOR)
    text->front->color |= TXT_CENTER;
    // asm 0000A2CB: 	LDI	*+AR1(TEXT_COLOR),R0
    // asm 0000A2CC: 	OR	TXT_CENTER,R0
    // asm 0000A2CD: 	STI	R0,*+AR1(TEXT_COLOR)
    text->shadow->color |= TXT_CENTER;
    // asm 0000A2CE: 	RETS
}

static void RIGHTEM(tSHADOW_TEXT* text) {
    // asm 0000A2CF: 	LDI	*+AR0(TEXT_COLOR),R0
    // asm 0000A2D0: 	OR	TXT_RIGHT,R0
    // asm 0000A2D1: 	STI	R0,*+AR0(TEXT_COLOR)
    text->front->color |= TXT_RIGHT;
    // asm 0000A2D2: 	LDI	*+AR1(TEXT_COLOR),R0
    // asm 0000A2D3: 	OR	TXT_RIGHT,R0
    // asm 0000A2D4: 	STI	R0,*+AR1(TEXT_COLOR)
    text->shadow->color |= TXT_RIGHT;
    // asm 0000A2D5: 	RETS
}

// *----------------------------------------------------------------------------
