#ifndef RACER_H
#define RACER_H

#include "../core/port.h"

/* Generated from asm/RACER.EQU. */

// RACER.EQU
//
// STARTING LINE INIT STRUCTURE
//
// RD STRUCT
// asm: RD_MODEL	.set	0	;UH
#define RD_MODEL 0 // UH

// asm: RD_POSITION	.set	1	;UD
#define RD_POSITION 1 // UD

// asm: RD_XLANE	.set	2	;FL
#define RD_XLANE 2 // FL

// asm: RD_MAXACCEL	.set	3	;FL
#define RD_MAXACCEL 3 // FL

// asm: RD_REL		.set	4	;FL
#define RD_REL 4 // FL

// asm: RD_PALETTE	.set	5	;UH
#define RD_PALETTE 5 // UH

// asm: RD_SIZE		.set	6	;SIZ
#define RD_SIZE 6 // SIZ

//
// PDATA PROCESS EQUATES
// (MOVED TO DELTA.EQU)
// ROADOFFSET	.SET	SUBDRNSTRT    	;TRACKING OFFSET TO CENTER OF ROAD
// POWERSURGE	.SET	SUBDRNSTRT+1   	;POWER SURGE VALUE
// POWERACERRCATCH	.SET	SUBDRNSTRT+2   	;POWER CATCHUP VALUE
// SURGETIME	.SET	SUBDRNSTRT+3   	;TIMER FOR NEW SURGE
// CATCHTIME	.SET	SUBDRNSTRT+4   	;TIMER FOR NEW CATCHUP
// STEALTHMODE	.SET	SUBDRNSTRT+5   	;STEALTH MODE FLAG 0=NO,1=AHEAD,-1=BEHND

// asm: RELATIVITY	.SET	SUBDRNSTRT+6   	;DRONE RELATIVE RATIO
#define RELATIVITY (SUBDRNSTRT + 6) // DRONE RELATIVE RATIO

// asm: INITINDEX	.SET	SUBDRNSTRT+7	;TEMP FOR INITTAB
#define INITINDEX (SUBDRNSTRT + 7) // TEMP FOR INITTAB

// asm: PASSCNT		.SET	SUBDRNSTRT+8	;TIMER TO INHIBIT PASS SND RETRIGGER
#define PASSCNT (SUBDRNSTRT + 8) // TIMER TO INHIBIT PASS SND RETRIGGER

// asm: FINISHDIST	.SET	SUBDRNSTRT+9	;FINISH DISTANCE
#define FINISHDIST (SUBDRNSTRT + 9) // FINISH DISTANCE

// asm: FINISHROT	.SET	SUBDRNSTRT+10	;FINISH ROTATION
#define FINISHROT (SUBDRNSTRT + 10) // FINISH ROTATION

// asm: 	.GLOBL	FINISH_ID,LEG_MAP,ROADIR,LEG_MAPI
extern int FINISH_ID;

extern LEG_PAYLOAD LEG_MAP[];

#define LEG_MAPI LEG_MAP

#define ENGFRI ENGFR

#define GEARACTABI GEARACTAB

#define ENGACTABI ENGACTAB

// asm: 	.GLOBL	PLYRFIRST,DRONESTOP,PLYRDRAFT,PLDRAFTVAL,CKAHEAD,STEERI
extern int PLYRFIRST;

extern c3x_f32_t STEERI;
extern c3x_f32_t GEARACTAB[5];
extern c3x_f32_t ENGACTAB[20];
extern c3x_f32_t ENGFR[5];

// asm: 	.globl	SPOS_INIT
c3x_reg_t SPOS_INIT(PROC* p /*AR7*/, OBJ* obj /*AR4*/, OBJ* tracking_obj /*AR2*/, int rank_forward /*AR3*/);

c3x_reg_t ROADIR(OBJ* track_obj /*AR0*/);

// asm: 	.GLOBL	GETRPM,GETAUTO,ENGFRI,GEARACTABI,ENGACTABI,GETRDIR
void GETRPM(CARBLK* carblk /*AR5*/);

int GETAUTO(CARBLK* carblk /*AR5*/);

c3x_reg_t GETRDIR(OBJ* track_obj /*AR2*/);

void DRONESTOP(OBJ* obj /*AR4*/, CARBLK* carblk /*AR5*/);

int CKAHEAD(OBJ* other_obj /*AR2*/, CARBLK* other_carblk /*AR3*/, OBJ* obj /*AR4*/, CARBLK* carblk /*AR5*/);

// RACER.ASM
// asm: 	.bss	FINISHNUM,1		;NUMBER OF DRONES FINISHED
extern int FINISHNUM;
// asm: 		.bss	RACER_PTR,10
extern OBJ* RACER_PTR[];
// asm: 	.bss	OM_TRACK_LO,1
extern int OM_TRACK_LO;
// asm: 	.bss	OM_TRACK_HI,1
extern int OM_TRACK_HI;
// asm: 	.BSS	ROADOBSTAB,50  		;ARRAY OF ROAD OBSTACLES
extern int ROADOBSTAB[];
// asm: 	.BSS	PLYRCLOSE,1		;CLOSING VELOCITY OF DRONE ON PLAYER
extern int PLYRCLOSE;
// asm: 	.BSS	CARTMP1,1
extern int CARTMP1;
int COMPTRAK(void);
OBJ* FIND_DYNA(int coded_id /*R2*/);
void DECODE_RACER_XSFER(void);
void WRECK(void);
void WRECKST(void);

#endif /* RACER_H */
