#ifndef RACER_H
#define RACER_H

/* Generated from asm/RACER.EQU. */

// RACER.EQU
// 
// COPYRIGHT (C) 1994 BY  TV GAMES, INC.
// ALL RIGHTS RESERVED

// 
// STARTING LINE INIT STRUCTURE
// 
// RD STRUCT
// asm: RD_MODEL	.set	0	;UH
#define RD_MODEL 0 //UH

// asm: RD_POSITION	.set	1	;UD
#define RD_POSITION 1 //UD

// asm: RD_XLANE	.set	2	;FL
#define RD_XLANE 2 //FL

// asm: RD_MAXACCEL	.set	3	;FL
#define RD_MAXACCEL 3 //FL

// asm: RD_REL		.set	4	;FL
#define RD_REL 4 //FL

// asm: RD_PALETTE	.set	5	;UH
#define RD_PALETTE 5 //UH

// asm: RD_SIZE		.set	6	;SIZ
#define RD_SIZE 6 //SIZ

// 
// PDATA PROCESS EQUATES
// (MOVED TO DELTA.EQU)
// ROADOFFSET	.SET	SUBDRNSTRT    	;TRACKING OFFSET TO CENTER OF ROAD
// POWERSURGE	.SET	SUBDRNSTRT+1   	;POWER SURGE VALUE
// POWERACERRCATCH	.SET	SUBDRNSTRT+2   	;POWER CATCHUP VALUE
// SURGETIME	.SET	SUBDRNSTRT+3   	;TIMER FOR NEW SURGE
// CATCHTIME	.SET	SUBDRNSTRT+4   	;TIMER FOR NEW CATCHUP
// STEALTHMODE	.SET	SUBDRNSTRT+5   	;STEALTH MODE FLAG 0=NO,1=AHEAD,-1=BEHND

// asm: RELATIVITY	.SET	SUBDRNSTRT+6   	;DRONE RELATIVE RATIO
#define RELATIVITY (SUBDRNSTRT+6) //DRONE RELATIVE RATIO

// asm: INITINDEX	.SET	SUBDRNSTRT+7	;TEMP FOR INITTAB
#define INITINDEX (SUBDRNSTRT+7) //TEMP FOR INITTAB

// asm: PASSCNT		.SET	SUBDRNSTRT+8	;TIMER TO INHIBIT PASS SND RETRIGGER
#define PASSCNT (SUBDRNSTRT+8) //TIMER TO INHIBIT PASS SND RETRIGGER

// asm: FINISHDIST	.SET	SUBDRNSTRT+9	;FINISH DISTANCE
#define FINISHDIST (SUBDRNSTRT+9) //FINISH DISTANCE

// asm: FINISHROT	.SET	SUBDRNSTRT+10	;FINISH ROTATION
#define FINISHROT (SUBDRNSTRT+10) //FINISH ROTATION

// asm: 	.GLOBL	FINISH_ID,LEG_MAP,ROADIR,LEG_MAPI
extern int FINISH_ID;

extern int LEG_MAP[MAX_LEG_ELEMENTS*LEG_SIZE];

#define LEG_MAPI LEG_MAP

#define ENGFRI ENGFR

#define GEARACTABI GEARACTAB

#define ENGACTABI ENGACTAB

// asm: 	.GLOBL	PLYRFIRST,DRONESTOP,PLYRDRAFT,PLDRAFTVAL,CKAHEAD,STEERI
extern int PLYRFIRST;

extern float STEERI;

// asm: 	.globl	SPOS_INIT
void SPOS_INIT(void);

void ROADIR(void);

// asm: 	.GLOBL	GETRPM,GETAUTO,ENGFRI,GEARACTABI,ENGACTABI,GETRDIR
void GETRPM(void);

void GETRDIR(void);

void DRONESTOP(void);

void CKAHEAD(void);

#endif /* RACER_H */
