#include "sndtaba.h"

#include "sndtab.h"
#include "sys.h"

/* Generated by tools/generate_sndtaba.py from asm/STABLE.INC. */
#define FRAMES 0x10000u
#define SPEECH (0x00ff | ENINT | CHAN1)

// SOUND ENTRY
//	SOND	LABEL,PRIORITY,TIME_AND_CODE<,PRIORITY,TIME_AND_CODE>
//
// PRIORITY WORD
//	.bits	EINNNNPPPPPPPP
//	I - 1 - NON INTERRUPTABLE
//	N - CHANNEL (0-3)
//	P - PRIORITY (0-255)
// TIME_AND_CODE
//	.nybles	TTTTCCCC
//	T - time in (0-7FFFh x 16ms)
//	C - code (0-7FFFh)
//

#define SOND(name, priority, time_and_code)             \
    [(name) / 3] = { (priority), (time_and_code) >> 16, \
        (time_and_code) & 0x7fff }

static const crusn_sound_entry SOUND_TABLE[] = {

    //----------------------------------------------------------------------------
    // HOTTUB SCENE
    //
    //
    SOND(MOO, 0x0FF | CHAN1, 54 * FRAMES | 290),

    SOND(LOWCOUNTRY, 0x0F0 | CHAN0, 3 * FRAMES | 369),
    SOND(THEPRES, 0x0F0 | CHAN3, 179 * FRAMES | 372),
    SOND(CLIN1, 0x0F0 | CHAN3, 3 * FRAMES | 355),
    SOND(CLIN2, 0x0F0 | CHAN3, 3 * FRAMES | 378),
    SOND(CLIN3, 0x0F0 | CHAN3, 3 * FRAMES | 381),
    SOND(CLIN4, 0x0F0 | CHAN3, 3 * FRAMES | 384),
    SOND(CLIN5, 0x0F0 | CHAN3, 3 * FRAMES | 387),
    SOND(CLIN6, 0x0F0 | CHAN3, 3 * FRAMES | 390),
    SOND(CLIN7, 0x0F0 | CHAN3, 3 * FRAMES | 393),
    SOND(CLIN8, 0x0F0 | CHAN3, 3 * FRAMES | 396),

    // CHANNEL 3 CALL
    SOND(CHICKCHEER, 0x60 | CHAN3, 1 * FRAMES | 490),

    SOND(BUGBUZZ, 0x0F0 | CHAN1, 3 * FRAMES | 429),
    SOND(DEER_CRASH, 0x0F0 | CHAN1, 37 * FRAMES | 426),

    SOND(STAMP1, 0x0FF | CHAN1, 70 * FRAMES | 550),
    SOND(WELCOME, SPEECH, 100 * FRAMES | 800),
    SOND(WHOOSH, 0x0FF | CHAN1, 62 * FRAMES | 105),

    SOND(LETTER_RIGHT, 0x050 | CHAN1, 3 * FRAMES | 546),
    SOND(STAMP, 0x0FF | CHAN2, 62 * FRAMES | 518),
    SOND(CHOOSE_LETTER, 0x0FF | CHAN2, 55 * FRAMES | 545),
    SOND(CLOSING, 0x50 | CHAN0, 60 * FRAMES | 20),

    SOND(ATTR_THEME, 0x10 | CHAN0, 2 * FRAMES | 28),
    SOND(METAL_SCRAPE, 0x10 | CHAN1, 2 * FRAMES | 151),

    SOND(KIDSCREAM1, 0x0FF | CHAN1, 120 * FRAMES | 560),
    SOND(KIDSCREAM2, 0x0FF | CHAN1, 108 * FRAMES | 562),

    SOND(NDETHSCREAM1, 0x0E0 | CHAN1, 158 * FRAMES | 650),
    SOND(NDETHSCREAM3, 0x0E0 | CHAN1, 52 * FRAMES | 656),
    SOND(NDETHSCREAM4, 0x0E0 | CHAN1, 151 * FRAMES | 659),
    SOND(NDETHSCREAM7, 0x0E0 | CHAN1, 144 * FRAMES | 668),
    SOND(MDETHSCREAM2, 0x0E0 | CHAN1, 105 * FRAMES | 443),
    SOND(MDETHSCREAM4, 0x0E0 | CHAN1, 131 * FRAMES | 449),
    SOND(MFDETHSCREAM1, 0x0E0 | CHAN1, 78 * FRAMES | 458),
    SOND(MFDETHSCREAM2, 0x0E0 | CHAN1, 78 * FRAMES | 461),
    // SOND(RADICAL, 0x0E0 | CHAN1, 49 * FRAMES | 772)
    // SOND(ROCKBABE, 0x0E0 | CHAN1, 56 * FRAMES | 774)
    SOND(ROAR, 0x0E0 | CHAN1, 75 * FRAMES | 622),
    SOND(BCHEER, 0x0E0 | CHAN1, 75 * FRAMES | 488),

    SOND(RK_SKREECH1, 0x050 | CHAN1, 36 * FRAMES | 564),
    SOND(RK_SPLAT1, 0x050 | CHAN1, 28 * FRAMES | 568),
    SOND(RK_SPLAT2, 0x050 | CHAN1, 39 * FRAMES | 570),
    SOND(GEESES, 0x050 | CHAN1, 2000 * FRAMES | 572),

    SOND(NINTENDO_SND, 0x010 | CHAN0, 829 * FRAMES | 30),

    SOND(DCSLOGOSND, 0x10 | CHAN1, 2 * FRAMES | 31),
    SOND(WIPE1, 0x10 | CHAN1, 2 * FRAMES | 602),
    SOND(WIPE2, 0x10 | CHAN1, 2 * FRAMES | 604),
    SOND(WIPE3, 0x10 | CHAN1, 2 * FRAMES | 606),
    SOND(WIPE4, 0x10 | CHAN1, 2 * FRAMES | 608),
    SOND(WIPE5, 0x10 | CHAN1, 2 * FRAMES | 610),
    SOND(CROWD1, 0x0Fe | ENINT | CHAN1, 300 * FRAMES | 620),
    SOND(CROWDROAR, 0x0Fe | CHAN1, 2 * FRAMES | 622),

    SOND(STARTLINEREVS2, 0x0BF | CHAN1, 30 * 7 * FRAMES | 626),

    SOND(PEELOUT, 0x0FF | CHAN1, 128 * FRAMES | 628),
    // SOND(SINGLEREV1, 0x10 | CHAN1, 2 * FRAMES | 630)
    // SOND(SINGLEREV2, 0x10 | CHAN1, 2 * FRAMES | 632)
    // SOND(SINGLEREV3, 0x10 | CHAN1, 2 * FRAMES | 634)
    // SOND(SINGLEREV4, 0x10 | CHAN1, 2 * FRAMES | 636)

    SOND(SINGLEREV5, 0x0C0 | CHAN1, 40 * FRAMES | 638),
    SOND(SINGLEREV6, 0x0C0 | CHAN1, 70 * FRAMES | 640),

    // SOND(FIRSTSND, 0x0F0 | CHAN3, 85 * FRAMES | 355)
    // SOND(SECONDSND, 0x0F0 | CHAN3, 190 * FRAMES | 356)
    // SOND(THIRDSND, 0x0F0 | CHAN3, 234 * FRAMES | 357)
    SOND(FOURTHSND, 0x0F0 | CHAN3, 190 * FRAMES | 358),
    SOND(DECELSND, 0x0F0 | CHAN3, 121 * FRAMES | 350),

    SOND(PASSBY1, 0x10 | CHAN1, 2 * FRAMES | 642),
    SOND(PASSBY2, 0x10 | CHAN1, 2 * FRAMES | 644),
    SOND(PASSBY3, 0x10 | CHAN1, 2 * FRAMES | 646),
    SOND(PASSBY4, 0x10 | CHAN1, 2 * FRAMES | 648),

    SOND(MAPSTAR2, 0x10 | CHAN1, 2 * FRAMES | 542),
    SOND(MAPSTARHIT, 0x10 | CHAN1, 2 * FRAMES | 544),

    SOND(JETFLYBY, 0x0FF | CHAN1, 274 * FRAMES | 534),

    SOND(WATERFALLSND, 0x0FF | CHAN1, 45 * FRAMES | 538),
    SOND(FIREHYDRSND, 0x10 | CHAN1, 2 * FRAMES | 540),

    SOND(GSWIPE1, 0x10 | CHAN1, 2 * FRAMES | 46),
    SOND(GSWIPE2, 0x10 | CHAN1, 2 * FRAMES | 47),
    SOND(MHIT, 0x10 | CHAN1, 2 * FRAMES | 518),
    SOND(DOPEN, 0x20 | CHAN1, 2 * FRAMES | 520),
    SOND(GOPEN, 0x10 | CHAN2, 2 * FRAMES | 522),
    SOND(DD1, 0x10 | CHAN1, 2 * FRAMES | 524),
    SOND(DD2, 0x10 | CHAN1, 2 * FRAMES | 530),
    SOND(HYDRO, 0x10 | CHAN1, 2 * FRAMES | 526),
    SOND(TRANS, 0x10 | CHAN1, 2 * FRAMES | 528),

    //----------------------------------------------------------------------------
    // MUSIC/TUNES
    //

    SOND(GETREADYTUNE, 0x10 | CHAN0, 2 * FRAMES | 27),
    SOND(MAPTUNE, 0x10 | CHAN0, 2 * FRAMES | 26),

    SOND(MUNSTER_SURF, 0x10 | CHAN0, 2 * FRAMES | 2),
    SOND(VENTURE, 0x10 | CHAN0, 2 * FRAMES | 10),

    SOND(SHUFFLE_DRIV, 0x10 | CHAN0, 2 * FRAMES | 4),
    SOND(STRAIGHT_2_4, 0x10 | CHAN0, 2 * FRAMES | 6),

    SOND(DISCODUCK, 0x10 | CHAN0, 2 * FRAMES | 24),

    SOND(BOOGIE, 0x10 | CHAN0, 2 * FRAMES | 13),
    SOND(SPAGETTI, 0x10 | CHAN0, 2 * FRAMES | 16),

    SOND(START_THEME, 0x10 | CHAN0, 2 * FRAMES | 21),
    SOND(OVER_THEME, 0x10 | CHAN0, 2 * FRAMES | 22),
    SOND(ENTER_INITS_THEME, 0x10 | CHAN0, 2 * FRAMES | 18),

    SOND(BONUS_THEME, 0x10 | CHAN0, 2 * FRAMES | 25),

    SOND(CHECKPT, SPEECH, 100 * FRAMES | 60),

    SOND(COININ, 0x0FF | CHAN1, 57 * FRAMES | 133),

    SOND(TEASE_TURNKEY, 10 | CHAN1, 2 * FRAMES | 400),

    SOND(GAMEOVR, 0x10 | CHAN0, 0x10000 | 20),
    SOND(VENTURE_ROLLHIT, 0x10 | CHAN0, 0x10000 | 13),
    //----------------------------------------------------------------------------

    //----------------------------------------------------------------------------
    // RAILROAD SOUNDS
    SOND(RR_BELL1, 0x0F0 | CHAN1, 15 * FRAMES | 204),
    SOND(RR_BELL2, 0x0F0 | CHAN1, 15 * FRAMES | 206),
    SOND(RR_TRAIN, 0x0F3 | CHAN1, 15 * FRAMES | 208),
    SOND(RR_HORNL, 0x0F0 | CHAN1, 108 * FRAMES | 210),
    SOND(RR_HORNS, 0x0F0 | CHAN1, 108 * FRAMES | 212),
    //----------------------------------------------------------------------------

    //----------------------------------------------------------------------------
    // COP STUFF

    SOND(COP_PULLOVER, SPEECH, 105 * FRAMES | 848),
    SOND(COP_STOP, SPEECH, 176 * FRAMES | 850),
    SOND(COP_STOP_RBLOCK, SPEECH, 176 * FRAMES | 852),
    SOND(COP_CROSS_RBLOCK, SPEECH, 178 * FRAMES | 854),

    SOND(SC_COPLONG, 0x042 | CHAN1, 10000 * FRAMES | 129),
    SOND(SC_COPSHORT, 0x042 | CHAN1, 10000 * FRAMES | 131),
    //----------------------------------------------------------------------------

    //----------------------------------------------------------------------------
    // VOICES
    // FX
    //

    // COCONUT
    SOND(COCONUTLOW, 0x50 | CHAN1, 16 * FRAMES | 123),
    SOND(COCONUTHI, 0x50 | CHAN1, 16 * FRAMES | 125),

    // HELICOPTER
    SOND(HELI_SNDLP, 0x0FE | CHAN1, 0x07FFF * FRAMES | 508),
    // 510 is al
    SOND(DIESEL_DOPPLER, 0x50 | CHAN1, 90 * FRAMES | 314),
    SOND(CAR_DOPPLER, 0x50 | CHAN1, 70 * FRAMES | 310),

    // GENERAL VOICE
    SOND(GV_TENSECONDS, 0x0FF | CHAN1, 60 * FRAMES | 782),

    SOND(GL_WOOLAUGH, SPEECH, 79 * FRAMES | 806),
    SOND(GL_YEAH, SPEECH, 31 * FRAMES | 810),
    SOND(GL_YES, SPEECH, 33 * FRAMES | 812),
    SOND(GL_YOUDIDIT, SPEECH, 52 * FRAMES | 814),

    // CHOOSE CAR
    SOND(CHOOSEUCAR, SPEECH, 68 * FRAMES | 714),
    SOND(CC_COOL, SPEECH, 68 * FRAMES | 720),
    SOND(CC_ROCK, SPEECH, 57 * FRAMES | 774),
    SOND(CC_BITCHIN, SPEECH, 39 * FRAMES | 704),
    SOND(CC_DIGIT, SPEECH, 23 * FRAMES | 722),

    // MISC ENVIRONMENT REACTIONS
    SOND(ER_SANFRANCISCO, SPEECH, 100 * FRAMES | 710),
    SOND(ER_WHITEHOUSE, SPEECH, 99 * FRAMES | 712),
    SOND(ER_MIDWEST, SPEECH, 78 * FRAMES | 746),
    SOND(ER_REDWOOD, SPEECH, 100 * FRAMES | 762),
    SOND(ER_HOLLYWOOD, SPEECH, 73 * FRAMES | 766),
    SOND(ER_GRANDCANYON, SPEECH, 98 * FRAMES | 778),
    SOND(ER_DEATHVALLEY, SPEECH, 85 * FRAMES | 804),
    SOND(ER_MTRUSHMORE, SPEECH, 93 * FRAMES | 808),

    // THE CHICK
    SOND(CHICK_READY, SPEECH, 29 * FRAMES | 734),
    SOND(CHICK_SET, SPEECH, 32 * FRAMES | 736),
    SOND(CHICK_GO, 0x0FF | CHAN1, 32 * FRAMES | 738),
    SOND(CHICK_SMOOCH, SPEECH, 2 * FRAMES | 748),
    SOND(CHICK_LAUGH, SPEECH, 2 * FRAMES | 750),
    SOND(CHICKSCREAM, SPEECH, 29 * FRAMES | 820),

    // RHO ABOUT TO HIT PLAYER
    SOND(RH_GOFORIT, SPEECH, 43 * FRAMES | 740),
    SOND(RH_TAKEHIM, SPEECH, 36 * FRAMES | 780),
    SOND(RH_GONNACRASH, SPEECH, 74 * FRAMES | 796),
    SOND(RH_BABESCREAM1, SPEECH, 96 * FRAMES | 776),
    SOND(RH_HURRYUP, SPEECH, 32 * FRAMES | 744),

    SOND(RH_BABEWHOA, SPEECH, 48 * FRAMES | 802),

    SOND(CARHORN, ENINT | 0x0D0 | CHAN1, 70 * FRAMES | 310),
    SOND(TRUCKHORN_BLAST, ENINT | 0x0D0 | CHAN1, 70 * FRAMES | 312),
    SOND(TRUCKHORN_DOPPLER, ENINT | 0x0D0 | CHAN1, 70 * FRAMES | 314),

    SOND(CARDOPL1, ENINT | 0x0D0 | CHAN1, 87 * FRAMES | 324),
    SOND(CARDOPL2, ENINT | 0x0D0 | CHAN1, 50 * FRAMES | 326),
    SOND(CARDOPL3, ENINT | 0x0D0 | CHAN1, 56 * FRAMES | 328),
    SOND(SEMIDOPL, ENINT | 0x0D0 | CHAN1, 56 * FRAMES | 330),
    SOND(BUSDOPL, ENINT | 0x0D0 | CHAN1, 63 * FRAMES | 334),
    //----------------------------------------------------------------------------

    //----------------------------------------------------------------------------
    //
    // PLAYER SOUND EFFECTS (TRACK 1 & 2)
    //

    //----------------------------------------------------------------------------
    //
    // PLAYER SOUND EFFECTS (TRACK 1 & 2)
    //

    // EXPLOSION SOUNDS
    SOND(EXP1, 0x070 | CHAN1, 101 * FRAMES | 512),
    SOND(EXP2, 0x070 | CHAN1, 140 * FRAMES | 514),
    SOND(EXP3, 0x070 | CHAN1, 74 * FRAMES | 516),

    // VIEW CHANGE
    SOND(VIEW2IN, 0x0F1 | CHAN1, 75 * FRAMES | 500),
    SOND(VIEW2OUT, 0x0F1 | CHAN1, 48 * FRAMES | 502),
    // SKIDS
    SOND(SKIDB, 0x50 | CHAN1, 10000 * FRAMES | 236),
    SOND(SKIDC, 0x50 | CHAN1, 10000 * FRAMES | 240),
    // SOND(SKIDD, 0x41 | CHAN1, 10000 * FRAMES | 236)
    // SOND(SKIDE, 0x41 | CHAN1, 10000 * FRAMES | 240)
    SOND(BRAKSND, 0x4F | CHAN1, 109 * FRAMES | 220),
    SOND(UPSHIFTSND, 0x0C0 | CHAN1, 10 * FRAMES | 238),

    // ROAD EFFECTS

    SOND(TUNSND, 0x42 | CHAN1, 10000 * FRAMES | 316),
    SOND(GRAVELA, 0x40 | CHAN1, 10000 * FRAMES | 266),

    // SHORT COLLISIONS (CAR VS. CAR)

    SOND(SCOLLA, 0x0F0 | CHAN1, 20 * FRAMES | 192),
    SOND(SCOLLB, 0x0F0 | CHAN1, 32 * FRAMES | 198),
    SOND(SCOLLC, 0x0F0 | CHAN1, 31 * FRAMES | 202),
    SOND(SCOLLD, 0x0F0 | CHAN1, 41 * FRAMES | 194),
    SOND(SCOLLE, 0x0F0 | CHAN1, 34 * FRAMES | 196),
    SOND(SCOLLF, 0x0F0 | CHAN1, 69 * FRAMES | 158),
    SOND(SCOLLG, 0x0F0 | CHAN1, 45 * FRAMES | 166),
    SOND(SCOLLH, 0x0F0 | CHAN1, 55 * FRAMES | 200),

    SOND(TRCOL1SND, 0x0FF | CHAN1, 140 * FRAMES | 514),
    SOND(TRCOL2SND, 0x0FF | CHAN1, 68 * FRAMES | 158),

    // CAR LANDS ON ROAD (BOTTOMOUT)
    SOND(BOTTOMOUT, 0x0F0 | CHAN1, 49 * FRAMES | 190),

    // WALL HIT SOUNDS  (CAR VS. WALL)
    SOND(WALLHITA, ENINT | 0x0F0 | CHAN1, 33 * FRAMES | 172),
    SOND(WALLHITB, ENINT | 0x0F0 | CHAN1, 28 * FRAMES | 174),
    SOND(WALLHITC, ENINT | 0x0F0 | CHAN1, 39 * FRAMES | 176),

    // FLYING DEBRIS HITS
    SOND(DRUMSND, 0x0F0 | CHAN1, 10 * FRAMES | 141),
    SOND(DRMBNCE, 0x48 | CHAN1, 10 * FRAMES | 141),
    SOND(SAWBNCE, 0x48 | CHAN1, 17 * FRAMES | 184),

    // DRONES HIT DEBRIS
    SOND(DSIGNSND, 0x048 | CHAN1, 20 * FRAMES | 188),

    // SIGN/POLE/TREE HIT
    SOND(POLESND, 0x0F0 | CHAN1, 20 * FRAMES | 168),
    SOND(SIGNSND, 0x0F0 | CHAN1, 20 * FRAMES | 188),
    SOND(LAMPSND, 0x0F0 | CHAN1, 20 * FRAMES | 137),
    SOND(DONGSND, 0x0F0 | CHAN1, 20 * FRAMES | 139),
    SOND(SAGESND, 0x0E0 | CHAN1, 20 * FRAMES | 135),
    SOND(SAGESND1, 0x0E0 | CHAN1, 20 * FRAMES | 145),
    SOND(SAGESND2, 0x0E0 | CHAN1, 20 * FRAMES | 143),
    SOND(SAGESND3, 0x0E0 | CHAN1, 20 * FRAMES | 182),

    // ENGINE SPUTTER SOUND
    SOND(SPUTSND, 0x0C0 | CHAN2, 40 * FRAMES | 412),

    SOND(REVSND1, 0x0C0 | CHAN3, 77 * FRAMES | 925),
    SOND(REVSND2, 0x0C0 | CHAN3, 45 * FRAMES | 926),
    SOND(REVSND3, 0x0C0 | CHAN3, 75 * FRAMES | 927),

    //----------------------------------------------------------------------------

    //----------------------------------------------------------------------------
    // RHO DRONE SOUNDS  (CAR PASSBYS)
    //
    SOND(CARPASS, 0x50 | CHAN1, 70 * FRAMES | 300),
    SOND(TRUCKPASS, 0x50 | CHAN1, 59 * FRAMES | 302),
    SOND(SMCARPASS, 0x50 | CHAN1, 45 * FRAMES | 304),
    SOND(FCARPASS, 0x50 | CHAN1, 50 * FRAMES | 306),
    SOND(SPCARPASS, 0x50 | CHAN1, 76 * FRAMES | 308),
    //----------------------------------------------------------------------------

    //----------------------------------------------------------------------------
    //

    SOND(TKEY, 0x50 | CHAN1, 0x3C0000 | 400),
    SOND(ENGINESTART, 0x50 | CHAN3, 0x10000 | 413),

    SOND(BASICBEEPH, 0x50 | CHAN1, 2 * FRAMES | 100),

    //----------------------------------------------------------------------------
    // DIAGNOSTIC/SYSTEM SOUNDS
    //
    //
    SOND(WPC_UP, 0x50 | CHAN2, 0x10000 | 980),
    SOND(WPC_DOWN, 0x50 | CHAN2, 0x10000 | 981),
    SOND(WPC_ENTER, 0x50 | CHAN2, 0x10000 | 982),
    SOND(WPC_ESCAPE, 0x50 | CHAN2, 0x10000 | 983),
    SOND(WPC_WARNING, 0x50 | CHAN2, 0x10000 | 984),
    SOND(WPC_SBEEP1, 0x50 | CHAN2, 0x10000 | 985),
    SOND(WPC_SBEEP2, 0x50 | CHAN2, 0x10000 | 986),
    SOND(WPC_MISC1, 0x50 | CHAN2, 0x10000 | 987),
    SOND(WPC_MISC2, 0x50 | CHAN2, 0x10000 | 988),
    SOND(WPC_MISC3, 0x50 | CHAN2, 0x10000 | 989),

    SOND(KILLCHAN0, 0x0FF | CHAN0, 0x10000 | 995),
    SOND(KILLCHAN1, 0x0FF | CHAN1, 0x10000 | 996),
    SOND(KILLCHAN2, 0x0FF | CHAN2, 0x10000 | 997),
    SOND(KILLCHAN3, 0x0FF | CHAN3, 0x10000 | 998),
    SOND(KILLALLS, 0x0FF | CHAN0, 0x10000 | 0),
    //
    // KILLALLS must be the LAST cound call in this file!!!
    //
    //----------------------------------------------------------------------------

};

#undef SOND
#undef SPEECH
#undef FRAMES

const crusn_sound_entry* crusn_sound_entry_from_index(int sound_index) {
    if (sound_index < 0 || sound_index % 3 != 0
        || (size_t)(sound_index / 3) >= crusn_sound_entry_count())
        return 0;
    return &SOUND_TABLE[sound_index / 3];
}

const crusn_sound_entry* crusn_sound_entry_from_dcs_track(unsigned dcs_track,
    int* channel) {
    size_t entry_index;

    for (entry_index = 0; entry_index < crusn_sound_entry_count(); ++entry_index) {
        if (SOUND_TABLE[entry_index].dcs_track == dcs_track) {
            *channel = (int)((SOUND_TABLE[entry_index].priority_word >> 8) & 0x0f);
            return &SOUND_TABLE[entry_index];
        }
    }

    /* SNDFX selects its second effects channel by incrementing the command. */
    for (entry_index = 0; entry_index < crusn_sound_entry_count(); ++entry_index) {
        int entry_channel = (int)((SOUND_TABLE[entry_index].priority_word >> 8) & 0x0f);
        if (entry_channel == 1 && SOUND_TABLE[entry_index].dcs_track + 1 == dcs_track) {
            *channel = 2;
            return &SOUND_TABLE[entry_index];
        }
    }

    return 0;
}

size_t crusn_sound_entry_count(void) {
    return sizeof(SOUND_TABLE) / sizeof(SOUND_TABLE[0]);
}
