#ifndef CMOS_H
#define CMOS_H

/* Generated from asm/CMOS.EQU. */
/*
 * CMOS.EQU
 * COPYRIGHT (C) 1994  BY TV GAMES, INC.
 * ALL RIGHTS RESERVED
 * ----------------------------------------------------------------------------
 * CMOS DEFINES
 * 8K X 8 CMOS RAM
 * BITS ARE:	TTTT TTTT xxxx xxxx xxxx xxxx xxxx xxxx
 * ADJUSTMENTS ARE FIRST, THEN AUDITS
 * ...
 */

/* Original .globl symbols in this module:
 *   CHECK_RACE_TABLE
 *   INSERT_TABLE_ENTRY
 *   TABLE_ENTRY_READ
 *   GET_TABLE_ADDR
 *   INIT_LASTHS_TABLE
 *   CHECK_LASTHS
 *   VALIDATE_HSTD_TABLES
 *   INIT_HSTD_TABLES
 *   FRAMTEST
 *   SRAMTEST
 *   CRAMTEST
 *   BITMAPTEST
 *   CHECK_RAM
 *   CMOSI
 *   HSTD_PAGEI
 *   ALL_TIME_HSTDI
 *   DAILY_HSTDI
 *   HSTD_DEFAULTI
 *   DAILY_DEFAULTI
 *   ADJUSTMENT_READ
 *   ADJUSTMENT_WRITE
 *   AUDIT_INC
 *   AUDIT_ADD
 *   AUDIT_READ
 *   AUDIT_WRITE
 *   GEN_CMOS_CHKSUM
 *   CHECK_CMOS
 *   CHKSUM_CMOS
 *   RESET_CMOS
 *   CLR_CMOS
 *   _wr_cw
 *   _rd_cw
 *   _wr_cwR
 *   _rd_cwR
 *   VALIDATE_CMOS
 *   CHECKSUM_PAGE
 *   GEN_CHECKSUM511
 *   SET_CHECKSUM
 *   RESET_BOOKKEEPING
 *   RESET_ADJUSTMENTS
 *   ENTER_DIAG
 *   BUMP_ALLTIME
 *   BUMP_DAILY
 *   CHECK_ALLTIME
 *   CHECK_DAILY
 *   CHECK_TABLE
 *   _HSTD_DISP
 *   _hstd_alltime
 *   RESET_ALL_TIME_CMOS
 *   RESET_DAILY_CMOS
 *   HSTD_DEFAULT
 *   DAILY_DEFAULT
 *   CMOS_ON_C
 *   CMOS_OFF_C
 *   CMOS_WPON_C
 *   CMOS_WPOFF_C
 */

#define CMWS 4 /* CMOS WORD SIZE */
#define ADJ_COINMODE 0 /* 0-50,0 */
#define ADJ_GASMIN 1 /* 0-255,0 */
#define ADJ_GASMAX 2 /* 0-255,255 */
#define ADJ_STEERMIN 3 /* 0-255,0 */
#define ADJ_STEERMAX 4 /* 0-255,255 */
#define ADJ_STEERCENTER 5 /* 0-255,128 */
#define ADJ_BRAKEMIN 6 /* 0-255,0 */
#define ADJ_BRAKEMAX 7 /* 0-255,255 */
#define ADJ_VOLUME 8 /* 0-255,255 */
#define ADJ_COIN1_UNITS 9 /* 0-100,1 */
#define ADJ_COIN2_UNITS 10 /* 0-100,1 */
#define ADJ_COIN3_UNITS 11 /* 0-100,1 */
#define ADJ_COIN4_UNITS 12 /* 0-100,1 */
#define ADJ_UNITS_PER_CREDIT 13 /* 0-100,1 */
#define ADJ_BONUS_UNITS 14 /* 0-100,0 */
#define ADJ_UNITS_MIN 15 /* 0-100,0 */
#define ADJ_CREDITS_TO_START 16 /* 0-100,3 */
#define ADJ_CREDITS_TO_CONTINUE 17 /* 0-100,3 */
#define ADJ_SHOW_FRAC 18 /* 0-1,1 */
#define ADJ_COIN1_COUNTER 19 /* 0-127,1 */
#define ADJ_COIN2_COUNTER 20 /* 0-127,1 */
#define ADJ_COIN3_COUNTER 21 /* 0-127,1 */
#define ADJ_COIN4_COUNTER 22 /* 0-127,4 */
#define ADJ_STANDARD_PRICING 23 /* 0-1,1 */
#define ADJ_CUSTOM_PRICING 24 /* 0-1,0 */
#define ADJ_FREE_PLAY 25 /* 0-1,0 */
#define ADJ_FREEGAME 26 /* 0-1,1 */
#define ADJ_DIFFICULTY 27 /* 0-10,7 */
#define ADJ_TIME_TO_START 28 /* 0-6,6 */
#define ADJ_CHECKPOINT_BONUS 29 /* 0-10,7 */
#define ADJ_ATTRACT_MODE_SOUND 30 /* 0-1,0 */
#define ADJ_HIGH_SCORE_ENTRY 31 /* 0-1,1 */
#define ADJ_MIN_VOL_LEVEL 32 /* 0-255,200 */
#define ADJ_ACTUALHSTDRESET 33 /* 0-25000,5000 */
#define ADJ_MPHORKPM 34 /* 0-1,0 */
#define ADJ_ROADKILL 35 /* 0-1,1 */
#define ADJ_CLINTON 36 /* 0-1,1 */
#define ADJ_GIRLS 37 /* 0-1,1 */
#define ADJ_STEERING_SENSITIVITY 38 /* 0-40,10 */
#define ADJ_HIGHSCORE_RESET 39 /* 1000,25000,5000 */
#define ADJ_DIFF_LOCAL 40 /* 0-100,50 */
#define ADJ_OUTOFDIAG 41 /* have we just left diag??? */
#define ADJ_RAMP_PERCENTAGE 42 /* 0-30,20 */
#define ADJ_RAMP_COUNT 43 /* 0-5000,0 */
#define ADJ_ENTER_INITS 44 /* 0-1,1 */
#define ADJ_MAX_CREDITS 45 /* 10-50,30 */
#define NUM_ADJUSTMENTS 46
#define ADJ_WDOG 50 /* temp space */
#define ADJ_INITIALS 51 /* -1 if reset x|b|b|b */
#define ADJ_MOTION_PRESENT 52
#define ADJ_CHECKSUM 53
#define MAX_ADJUSTMENTS 54
#define AUD_COIN1 100 /* * */
#define AUD_COIN2 101 /* * */
#define AUD_COIN3 102 /* * */
#define AUD_COIN4 103 /* * */
#define AUD_SERVICE_CREDITS 104 /* * */
#define AUD_PAID_CREDITS 105 /* * */
#define AUD_TOTAL_FREEGAMES 106
#define AUD_FREE_TO_TOTAL 107 /* % FREE GAMES TO TOTAL PLAYS */
#define AUD_TOTAL_PLAYS 108
#define AUD_TOTAL_STARTS 109
#define AUD_TOTAL_CONTINUES 110
#define AUD_GAMENUMBER 111
#define AUD_PCREDITS 112 /* partial credits */
#define AUD_CREDITS 113 /* actual credits */
#define AUD_NUM_BUYINS 114
#define AUD_TOTAL_TIME 115 /* AUD_TOTAL_TIME/AUD_NUM_BUYINS / 100 */
#define AUD_AVG_TIME 116
#define AUD_NUM_UNFINISHED 117
#define AUD_POWERON_TIME 118 /* Measured in seconds... */
#define AUD_GAMEON_TIME 119 /* Measured in seconds... */
#define AUD_NUM_WATCHDOGS 120
#define AUD_TOTAL_UNLINKED_PLAYS 121
#define AUD_TOTAL_UNLINKED_1STS 122
#define AUD_UNLINKED_1ST_TO_TOTAL_UL 123
#define AUD_TOTAL_UNLINKED_STARTS 124
#define AUD_TOTAL_UNLINKED_CONTINUES 125
#define AUD_CONTINUES_TO_PLAYS_UNLINKED 126
#define AUD_TOTAL_UNLINKED_GAME_ENDS 127
#define AUD_RESET_TOTALLY 128
#define AUD_LINKED_1ST_TO_TOTAL_UL 129
#define AUD_TOTAL_LINKED_STARTS 130
#define AUD_TOTAL_LINKED_CONTINUES 131
#define AUD_CONTINUES_TO_PLAYS_LINKED 132
#define AUD_TOTAL_LINKED_GAME_ENDS 133
#define AUD_LINKED_PLAYS_TO_TOTAL_PLAYS 134
#define AUD_TOTAL_ONTIME 135
#define AUD_TOTAL_PLAYTIME 136
#define AUD_TOTAL_LINKED_PLAYTIME 137
#define AUD_TOTAL_UNLINKED_PLAYTIME 138
#define AUD_AVG_TIME_PER_CREDIT 139
#define AUD_AVGCREDITS_PER_GAME 140
#define AUD_COIN_DOOR_SLAMS 141
#define AUD_SUCCESSFULL_BURNINS 142
#define AUD_UNFINISHED_GAMES 143
#define AUD_UNFINISHED_GAMES_FOUND 144
#define AUD_VIEW1_TIME 145
#define AUD_VIEW2_TIME 146
#define AUD_VIEW3_TIME 147
#define AUD_RADIO_HITS 148 /* * */
#define AUD_AUTOMATIC_TRANS_SELECTED 149 /* * */
#define AUD_MANUAL_TRANS_SELECTED 150 /* * */
#define AUD_GAMES_EXPIRED 151
#define AUD_GENERAL_CHKSUM 152
#define AUD_START_GGATE 153
#define AUD_FINISH_GGATE 154
#define AUD_START_SF 155
#define AUD_FINISH_SF 156
#define AUD_START_US101 157
#define AUD_FINISH_US101 158
#define AUD_START_REDWOOD 159
#define AUD_FINISH_REDWOOD 160
#define AUD_START_BEVHILLS 161
#define AUD_FINISH_BEVHILLS 162
#define AUD_START_LA 163
#define AUD_FINISH_LA 164
#define AUD_START_DV 165
#define AUD_FINISH_DV 166
#define AUD_START_ARIZONA 167
#define AUD_FINISH_ARIZONA 168
#define AUD_START_GC 169
#define AUD_FINISH_GC 170
#define AUD_START_IOWA 171
#define AUD_FINISH_IOWA 172
#define AUD_START_CHICAGO 173
#define AUD_FINISH_CHICAGO 174
#define AUD_START_INDIANA 175
#define AUD_FINISH_INDIANA 176
#define AUD_START_APPALACHIA 177
#define AUD_FINISH_APPALACHIA 178
#define AUD_START_DC 179
#define AUD_FINISH_GAME 180
#define AUD_WIN_GGATE 181
#define AUD_WIN_SF 182
#define AUD_WIN_US101 183
#define AUD_WIN_REDWOOD 184
#define AUD_WIN_BEVHILLS 185
#define AUD_WIN_LA 186
#define AUD_WIN_DV 187
#define AUD_WIN_ARIZONA 188
#define AUD_WIN_GC 189
#define AUD_WIN_IOWA 190
#define AUD_WIN_CHICAGO 191
#define AUD_WIN_INDIANA 192
#define AUD_WIN_APPALACHIA 193
#define AUD_WIN_DC 194
#define AUD_WIN_GAME 195
#define AUD_GAMES_START 210
#define AUD_GAMES_CONTINUES 211
#define AUD_GAMES_ENDS 212
#define AUD_BURNINS 213
#define AUD_VERTFRAME 214
#define AUD_POLYFRAME 215
#define AUD_OBJFRAME 216
#define AUD_FRAMEFRAME 217
#define AUD_REPEAT_REDWOOD 218
#define AUD_REPEAT_DEATHVALLEY 219
#define AUD_REPEAT_GRANDCANYON 220
#define AUD_REPEAT_CHICAGO 221
#define AUD_LOG_COUNT 222
#define AUD_LAST_LEG 223 /* LAST LEG SETUP */
#define AUD_PLAYS_TO_HISCORE_RESET 224
#define AUD_VETTE_SELECTED 225
#define AUD_CAR_SELECTION AUD_VETTE_SELECTED
#define AUD_LABOMBA_SELECTED 226
#define AUD_DEVASTATOR_SELECTED 227
#define AUD_ITALIA_SELECTED 228
#define AUD_HID_JEEP_SELECTED 229
#define AUD_HID_SBUS_SELECTED 230
#define AUD_HID_COPCAR_SELECTED 231
#define AUD_HID_DIESEL_SELECTED 232
#define AUD_FS_AZ 233 /* free select ARIZONA */
#define AUD_FS_US101 234
#define AUD_FS_LA 235
#define AUD_FS_IOWA 236
#define AUD_FS_DV 237
#define AUD_FS_USA 238
#define AUD_FS_BH 239
#define AUD_FS_APPL 240
#define AUD_FS_RW 241
#define AUD_FS_RM 242
#define AUD_FS_CH 243
#define AUD_FS_HID_SF 244
#define AUD_FS_HID_IN 245
#define AUD_FS_HID_GG 246
#define AUD_BCREDITS 247
#define AUD_H2HGAMES 248
#define NUM_AUDITS 249
#define AUD_VERSION 250
#define AUD_HIGHSCORE_CHECKSUM 251
#define AUD_CHIPTEST_DEDICATED 252
#define AUD_CHECKSUM 253
#define MAX_AUDITS 254
#define TE_TIME 0 /* TIME */
#define TE_INIT1 4 /* } */
#define TE_INIT2 5 /* } PLAYERS INITIALS */
#define TE_INIT3 6 /* } */
#define TE_RANK 7 /* RANK */
#define TE_SIZE 8
#define NUM_RACES 15
#define NUM_ENTRIES_PER_RACE 10
#define RACE_TABLE_SIZE (NUM_ENTRIES_PER_RACE*TE_SIZE)
#define CMOS_PAGE 0x0800 /* page size (2048b in length, 512 words) */
#define HSTD_PAGE (CMOS+(MAX_AUDITS*4))
#define H280_RTABLE HSTD_PAGE
#define SF_RTABLE (HSTD_PAGE+(RACE_TABLE_SIZE))
#define RW_RTABLE (HSTD_PAGE+(RACE_TABLE_SIZE*1))
#define BEVLA_RTABLE (HSTD_PAGE+(RACE_TABLE_SIZE*2))
#define DVAZ_RTABLE (HSTD_PAGE+(RACE_TABLE_SIZE*3))
#define GC_RTABLE (HSTD_PAGE+(RACE_TABLE_SIZE*4))
#define IO_RTABLE (HSTD_PAGE+(RACE_TABLE_SIZE*5))
#define CH_RTABLE (HSTD_PAGE+(RACE_TABLE_SIZE*6))
#define AP_RTABLE (HSTD_PAGE+(RACE_TABLE_SIZE*7))
#define DC_RTABLE (HSTD_PAGE+(RACE_TABLE_SIZE*8))

#endif /* CMOS_H */
