#ifndef CORNOBJ_H
#define CORNOBJ_H

/* Generated from asm/CORNOBJ.EQU. */
/*
 * OBJECTS.EQU
 * COPYRIGHT (C) 1994 TV GAMES, INC.
 * ALL RIGHTS RESERVED
 * Generated by PComp v2.41
 * num_palettes	.set	1
 * cornpops_p          	.set	0
 * num_objects	.set	1
 * num_sections	.set	1
 * ...
 */

/* Original .globl symbols in this module:
 *   _SECcorn
 *   corn_PALETTES
 */

#define cornpops 0x0C14482
#define cornpops_I 0x03D2C
#define CORNPAL 0x0C14400

#endif /* CORNOBJ_H */
