#ifndef DELTA_H
#define DELTA_H

/* Generated from asm/DELTA.EQU. */
/*
 * DELTA.EQU
 * COPYRIGHT (C) 1994 BY  TV GAMES, INC.
 * ALL RIGHTS RESERVED
 * DELTAX_MAX		.set	1920
 * DELTAX_MAX_2LN		.set	1050
 * ***	DELTA.ASM
 * ***	SIGMA.ASM
 * ***	RHO.ASM
 * ...
 */

/* Original .globl symbols in this module:
 *   SUSPEND_MODE
 *   RACER_PTRI
 *   RACER_PTR
 *   DELTA_OINIT
 *   GET_TRACK_POS
 *   GET_TRACK_POS_RVS
 *   GET_TRACK_POS_RVS_XLANE
 *   DELTA_GET_TRACK_POS
 *   DELTA_SUB_FUNCTION
 *   LANEPI
 *   LANEP
 *   LANESI
 *   LANES
 *   LANES4
 *   LANESI
 *   LANES
 *   LANE2MLT
 *   LANE4MLT
 *   VEHICLESI
 *   VEHICLES
 *   SIGMA_DRONE
 *   RHO_DRONE
 *   RHO_DIE
 *   CHOPPER
 *   AHEAD_OF_PLAYER_P
 *   REGISTER_RACER
 *   SET_DRONE_PAL
 *   TRAFFIC
 *   GET_LANES
 *   DIST_TO_PLYR
 *   INIT_TRACKING_PIECE
 *   GET_TRACK_POS_RVS
 *   GET_TRACK_POS
 *   GET_TRACK_POS_RVS_XLANE
 *   SUB_FUNCTION_RVS
 *   SUB_FUNCTION
 *   SUB_FUNCTION_RVS_XLANE
 *   SUB_FUNCTION_XLANE
 *   INIT_DRONES
 *   ADD_DRONE
 *   FREE_DRONE
 *   PTS
 *   FIND_PLYR_RANK
 *   PRECOLLIDE_PLYR
 *   DRONE_RIDE_RIGHT
 *   AVOID_CAR_OBSTACLES
 *   ROAD_MAPI
 *   RACER_GRID_START
 *   REGISTER
 */

#define DELTA_SAFETYWIDTH 850
#define DELTA_WIDTH 500
#define DELTA_HALF_WIDTH 300
#define DELTAX_MIN 0
#define DELTAX_MAX 2020
#define DELTAX_MAX_2LN 1050
#define MAX_DRONES 11 /* MAXIMUM DRONES IN UNIVERSE */
#define REGRAC_POSITION 0 /* UD	THIS IS COMPUTED */
#define REGRAC_OBJECT 1 /* UH	PTR TO RACER #X OBJECT */
#define REGRAC_CARBLOCK 2 /* UH	PTR TO RACER #X CARBLOCK */
#define REGRAC_PROC 3 /* UH	PTR TO RACER #X PROCESS */
#define REGRAC_SIZE 4 /* SIZ */
#define NUM_RACERS 8
#define SM_GO 0x5577 /* REGULAR DRONE PROCESSING */
#define SM_HALT 0x33BB /* FREEZE DRONES ... DONT MOVE (COIN IN, ETC.) */
#define THROTTLE_INIT 0.8
#define MIN_THROTTLE 0.35
#define MIN_FBTHROTTLE 0.65
#define MAX_THROTTLE 1.0
#define FREE_THROTTLE 0.65 /* MAX_THROTTLE-MIN_THROTTLE */
#define MAX_SIGMA_THROTTLE 0.50
#define MAX_COPCAR_THROTTLE 0.50
#define RHO_MAX_ACCEL_INIT 0.40 /* (0.82 == PLYR) */
#define MAX_ACCEL_INIT 0.70 /* (0.82 == PLYR) */
#define DELTA_MAX_ACCEL_INIT 0.90 /* (0.82 == PLYR) */
#define DELTA_STATUS (PDATA+0) /* UH	GENERAL STATUS */
#define DELTA_RADYDELTA (PDATA+1) /* UH	Y theta Delta */
#define DELTA_INIT (PDATA+2) /* SD	INITIAL POSITION PARAMETER */
#define DELTA_THROTTLE (PDATA+3) /* FL	throttle level */
#define DELTA_TPIECE (PDATA+4) /* UH	ROAD TRACKED PIECE */
#define DELTA_MODE (PDATA+5) /* UH	TRACKING MODE FLAGS (NORMAL/STEALTH) */
#define DELTA_SPTR (PDATA+6) /* UH	STEALTH POINTER */
#define DELTA_LAST_OID (PDATA+7) /* UH	*LAST KNOWN OID TO SEARCH FOR */
#define DELTA_PSTAT (PDATA+8) /* UH	0=behind plyr, 1=ahead of plyr */
#define DELTA_PLAYIT (PDATA+9) /* UH	WAY THE GAME IS BEING PLAYED */
#define PLAYIT_LOGIC 0x0FF00
#define KAMIKAZE 0x00200
#define FALL_BACK 0x00300
#define DELTA_LANE (PDATA+10) /* FL	LANE */
#define DELTA_PLYRDIST (PDATA+11) /* FL */
#define DELTA_OPLYRDIST (PDATA+12) /* FL */
#define DELTA_MODEL (PDATA+13) /* UD */
#define DELTA_LANE_SWITCH_TMR (PDATA+14) /* UD */
#define DELTA_XLANE (PDATA+15) /* UD	extended lanes */
#define DELTA_MIN_THROTTLE (PDATA+16) /* FL */
#define DELTA_MAX_THROTTLE (PDATA+17) /* FL */
#define DELTA_UPDATE_FL (PDATA+18) /* UD	comm update flag 1=just updated */
#define SUBDRNSTRT (PDATA+20)
#define RHO_NOISE (SUBDRNSTRT+0) /* UH	FLG WHETHER IT HAS RAZZED THE PLYR */
#define RHO_YELL (SUBDRNSTRT+1) /* UH	FLG WHETHER IT HAS YELLED THE PLYR */
#define RHO_INIT (SUBDRNSTRT+2) /* UH	IDX INITIAL RHO TYPE */
#define RHO_THETA (SUBDRNSTRT+3) /* FL */
#define RHO_THETA_DELTA (SUBDRNSTRT+4) /* FL */
#define RHO_AMP (SUBDRNSTRT+5) /* FL */
#define RHO_XHEAD (SUBDRNSTRT+6) /* FL */
#define SIGMA_ONCE (SUBDRNSTRT+0) /* UH	FLG THE DRONE HAS BEEN ON AT LEAST ONCE (BREAKDOWN FLAG) */
#define SIGMA_YELL (SUBDRNSTRT+1) /* UH	FLG WHETHER PLYR HAS RAZZED THE SIGMA */
#define SIGMA_MODEL (SUBDRNSTRT+2)
#define SIGMA_FLAG (SUBDRNSTRT+3)
#define COPCAR_ONCE (SUBDRNSTRT+1) /* UH	FLG THE DRONE HAS BEEN ON AT LEAST ONCE (BREAKDOWN FLAG) */
#define COPCAR_CHASE (SUBDRNSTRT+2)
#define COPCAR_REACTION (SUBDRNSTRT+3) /* FL	0.1-1.0  DELTA_XLANE ratio tracking */
#define COPCAR_SPEED_MOD (SUBDRNSTRT+4) /* FL	overtake speed varience */
#define COPCAR_SIREN (SUBDRNSTRT+5) /* UH	sound call to use */
#define ROADOFFSET SUBDRNSTRT /* TRACKING OFFSET TO CENTER OF ROAD */
#define POWERSURGE (SUBDRNSTRT+1) /* POWER SURGE VALUE */
#define POWERCATCH (SUBDRNSTRT+2) /* POWER CATCHUP VALUE */
#define SURGETIME (SUBDRNSTRT+3) /* TIMER FOR NEW SURGE */
#define CATCHTIME (SUBDRNSTRT+4) /* TIMER FOR NEW CATCHUP */
#define STEALTHMODE (SUBDRNSTRT+5) /* STEALTH MODE FLAG 0=NO,1=AHEAD,-1=BEHND */
#define DM_MMODE 0x0FF /* MODE MASK */
#define DM_NORMAL 1 /* REGULAR DYNAfLEX TRACKING MODE */
#define DM_STEALTH 2 /* STEALTH (MAP) TRACKING MODE (LINEAR) */
#define DM_ST_BEYOND 0x100 /* ENTERED BECAUSE TO FAR AHEAD */
#define DM_ST_BELOW 0x200 /* ENTERED BECAUSE TO FAR BEHIND */
#define DELTA_STATUS_LANE 0x03
#define VETTE_MOD 0
#define HOTROD_MOD 1
#define BULLET_MOD 2
#define TESTOR_MOD 3
#define GTRUCK_MOD 4
#define FTRUCK_MOD 5
#define CBUS_MOD 6
#define COPCAR_MOD 7
#define MUSCLE_MOD 8
#define CARAVAN_MOD 9
#define SBUS_MOD 10
#define PTRUCKG_MOD 11
#define MUSTANG_MOD 12
#define JEEP_MOD 14
#define PLYR_COPCAR_MOD 15
#define PLYR_GTRUCK_MOD 16
#define PLYR_SBUS_MOD 17

#endif /* DELTA_H */
