#ifndef H2HOBJ_H
#define H2HOBJ_H

/* Generated from asm/H2HOBJ.EQU. */
/*
 * OBJECTS.EQU
 * COPYRIGHT (C) 1994 TV GAMES, INC.
 * ALL RIGHTS RESERVED
 * Generated by PComp v2.41
 * num_palettes	.set	3
 * p1_p                	.set	0
 * redhd1_p            	.set	1
 * big2_p              	.set	2
 * ...
 */

/* Original .globl symbols in this module:
 *   _SEChead2head
 */

#define h2p1 0x0C1400F
#define h2p1_I 0x03DF4
#define h2p2 0x0C1401F
#define h2p2_I 0x03DF4
#define h2p1a 0x0C1402F
#define h2p1a_I 0x03DF4
#define h2p2b 0x0C1403F
#define h2p2b_I 0x03DF4
#define redhd1 0x0C140D0
#define redhd1_I 0x03E1E
#define yelhd1 0x0C140E0
#define yelhd1_I 0x03E1E
#define big2 0x0C14171
#define big2_I 0x03F5B
#define head2head 0x0AF7D00 /* 7940 */
#define H2HPAL1 0x0C14000
#define H2HPAL2 0x0C1404E
#define H2HPAL3 0x0C140EF

#endif /* H2HOBJ_H */
