#ifndef INFIN_H
#define INFIN_H

/* Generated from asm/INFIN.ASM. */

// asm: 	.bss	CAMRADY,1  	;NORMALIZED 0-2PI CAMERA RAD
#define CAMRADY 0x0000E428
// asm: 	.bss	HIGHEST_ROADY,1		;FL	CLIP LEVEL IN Y
#define HIGHEST_ROADY 0x0000E429
// asm: 	.bss	HIGHEST_ROADY_X,1	;FL	CLIP LEVEL IN Y
#define HIGHEST_ROADY_X 0x0000E42A
// asm: 	.bss	VAR_ROAD_KFACTOR,1	;FL	CLIPPING OVERSHOOT FACTOR
#define VAR_ROAD_KFACTOR 0x0000E42B
// asm: 		.bss	AMOUNT_CLIPPED,1
#define AMOUNT_CLIPPED 0x0000E42C
// asm: 	.bss	INFIN_CORRECT,1
#define INFIN_CORRECT 0x0000E42D

#endif /* INFIN_H */
