#ifndef MPROC_H
#define MPROC_H

/* Generated from asm/MPROC.ASM. */

// asm: 	.bss	CURRENT_PROC,1		;CURRENT PROCESS POINTER (DEBUG ONLY!)
#define CURRENT_PROC 0x0000C9AE
// asm: 	.bss	OLDSP,1	    		;SAVE OLD STACK POINTER
#define OLDSP 0x0000C9AF
// asm: 	.bss	PACTIVE,1		;ACTIVE PROCESS LIST POINTER
#define PACTIVE 0x0000C9B0
// asm: 	.bss	PFREE,1			;FREE PROCESS LIST POINTER
#define PFREE 0x0000C9B1
// asm: 	hibss	PRCSTR,PRCSIZ*NUMPROC	;PROCESS STORE AREA
#define PRCSTR 0x0000EC17

#endif /* MPROC_H */
