#ifndef PALL_H
#define PALL_H

/* Generated from asm/PALL.ASM. */

// asm: 	.bss  	PALRAM,PALNUM		;ACTIVE PALETTES
#define PALRAM 0x0000C9BD
// asm: 	.bss	RAWLOCS,PALNUM
#define RAWLOCS 0x0000CA3D
// asm: 	.bss	PTTRAM,PALNUM*3		;PALLETTE TRANSFER RAM
#define PTTRAM 0x0000CABD
// asm: 	.bss	PALXFER_ACTIVE,1
#define PALXFER_ACTIVE 0x0000CC3F
// asm: 	.bss	PALXFER_FREE,1
#define PALXFER_FREE 0x0000CC40
// asm: 	.bss	PALXFER_AVAILABLE_P,1
#define PALXFER_AVAILABLE_P 0x0000CC41
// asm: 	.bss	PALXFER_STR,PALX_SIZE*NXFER_PALS
#define PALXFER_STR 0x0000CC42

#endif /* PALL_H */
