#include "../../core/cpu.h"
#include "../../core/machine.h"

/*
 * Source module: asm/CORNOBJ.ASM
 */

// *
// *COPYRIGHT (C) 1994 TV GAMES, INC.
// *ALL RIGHTS RESERVED
// *
// *Generated by PComp v2.41
// *
// ;	.def	_PALLIST,_PALROM
// ;	.bss	_PALLIST,256
// ;_PALROM:
// ;	.word	0C14400h
// ;	.globl	TYCO_TRKI
// ;TYCO_TRKI:	.word	00h
// ;	.globl	ROAD_MAPI
// ;ROAD_MAPI:	.word	00h
// ;
// 	;SECTION DATA
/* asm: _SECcorn:		;(15779 lines, 98.62%) */
/* asm: 	.word	0C16800h	;Src (Compressed) Addr */
/* asm: 	.word	0BE9600h	;Dest Addr */
/* asm: 	;	.globl	corn_PALETTES */
/* asm: 	;corn_PALETTES: */
/* asm: 	;	.word	0,0 */
int _SECcorn[2] = {
    0x0C16800, // Src (Compressed) Addr
    0x0BE9600, // Dest Addr
};

void cornobj(void)
{
    UNIMPL();
}
