#include "../../core/cpu.h"
#include "../../core/machine.h"

/*
 * Source module: asm/CORNOBJ.ASM
 */

// *
// *COPYRIGHT (C) 1994 TV GAMES, INC.
// *ALL RIGHTS RESERVED
// *
// *Generated by PComp v2.41
// *
// ;	.def	_PALLIST,_PALROM
// ;	.bss	_PALLIST,256
// ;_PALROM:
// ;	.word	0C14400h
// ;	.globl	TYCO_TRKI
// ;TYCO_TRKI:	.word	00h
// ;	.globl	ROAD_MAPI
// ;ROAD_MAPI:	.word	00h
// ;
// 	;SECTION DATA

void _SECcorn(void)
{
    //  ;(15779 lines, 98.62%)
    // ;	.globl	corn_PALETTES
    // ;corn_PALETTES:
    // ;	.word	0,0
    /* no executable asm lines detected */
    UNIMPL();
}
