#include "../../core/cpu.h"
#include "../../core/machine.h"

/*
 * Source module: asm/H2HOBJ.ASM
 */

// *
// *COPYRIGHT (C) 1994 TV GAMES, INC.
// *ALL RIGHTS RESERVED
// *
// *Generated by PComp v2.41
// *
// ;	.def	_PALLIST,_PALROM
// ;	.bss	_PALLIST,256
// ;_PALROM:
// ;	.word	0C14000h,0C1404Eh,0C140EFh
// ;	.globl	TYCO_TRKI
// ;TYCO_TRKI:	.word	00h
// ;	.globl	ROAD_MAPI
// ;ROAD_MAPI:	.word	00h
// ;
// 	;SECTION DATA
/* asm: _SEChead2head:		;(16345 lines, 102.16%) */
/* asm: 	.word	0C15000h	;Src (Compressed) Addr */
/* asm: 	.word	0BEFA00h	;Dest Addr */
/* asm: 	;	.globl	head2head_PALETTES */
/* asm: 	;head2head_PALETTES: */
/* asm: 	;	.word	0,0 */
/* asm: 	; */
int _SEChead2head[2] = {
    0x0C15000, // Src (Compressed) Addr
    0x0BEFA00, // Dest Addr
};

void h2hobj(void)
{
    UNIMPL();
}
