#include "../../core/cpu.h"
#include "../../core/machine.h"

/*
 * Source module: asm/INVTAB30.ASM
 */

// *----------------------------------------------------------------------------
// *INVERSE MULTIPLIER TABLE
// *
// *COPYRIGHT (C) 1994  BY TV GAMES, INC.
// *ALL RIGHTS RESERVED
// *
// *Generated by: C:\VIDEO\TABLES\INVGEN.EXE  Apr 29 1992
// *X = X * INVERSE[ Z / 16 ]
// *
// *1 <= Z <= 80000
// *About 4999.94k
// *
// *with hand modifications -ELP
// *

void INVTAB(void)
{
    /* no executable asm lines detected */
    UNIMPL();
}
