#include "../../core/cpu.h"
#include "../../core/machine.h"

/*
 * Source module: asm/OBJECTS.ASM
 */

// *
// *COPYRIGHT (C) 1994 TV GAMES, INC.
// *ALL RIGHTS RESERVED
// *
// *Generated by PComp v2.41
// *
// ;	.def	_PALLIST,_PALROM
// ;	.bss	_PALLIST,256
// ;_PALROM:
// ;	.word	0C14000h,0C1404Eh,0C140EFh
// ;	.globl	TYCO_TRKI
// ;TYCO_TRKI:	.word	00h
// ;	.globl	ROAD_MAPI
// ;ROAD_MAPI:	.word	00h
// ;
// 	;SECTION DATA

void _SEChead2head(void)
{
    //  ;(16345 lines, 102.16%)
    // ;	.globl	head2head_PALETTES
    // ;head2head_PALETTES:
    // ;	.word	0,0
    // ;
    /* no executable asm lines detected */
    UNIMPL();
}
