#!/usr/bin/env python3

# mame crusnusa -window -sound none -debug -log -skip_gameinfo -debugscript tools/mame/output/mame_validate_word_breakpoints.txt
from __future__ import annotations

import argparse
import pathlib
import re
from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional

ROOT = pathlib.Path(__file__).resolve().parents[2]

VALIDATE_RE = re.compile(
    r'mame_validate_word\(\s*"(?P<label>[^"]+)"\s*,\s*&(?P<var>[A-Za-z_][A-Za-z0-9_]*)\s*\)\s*;'
)
ASM_ADDR_RE = re.compile(r"^\s*//\s*asm\s+(?P<addr>[0-9A-Fa-f]{8}):")
ADDRESS_MAP_RE = re.compile(r"^\s*[0-9A-Fa-f]{4}:([0-9A-Fa-f]{8})\s+(.+?)\s*$")


@dataclass(frozen=True)
class BreakpointEntry:
    label: str
    variable_name: str
    variable_address: int
    next_instruction_address: int
    source_path: pathlib.Path
    source_line: int

    def format_mame(self, action: str = "g") -> str:
        return (
            f'bpset {self.next_instruction_address:08X}, 1, '
            f'{{ logerror "validate {self.label}: 0x%08X\\n", d@{self.variable_address:08X}; {action} }}'
        )


def parse_address_map(map_path: pathlib.Path) -> Dict[str, int]:
    out: Dict[str, int] = {}
    if not map_path.exists():
        return out
    for line in map_path.read_text(errors="ignore").splitlines():
        match = ADDRESS_MAP_RE.match(line)
        if not match:
            continue
        out.setdefault(match.group(2), int(match.group(1), 16))
    return out


def lookup_label_address(label: str, address_map: Dict[str, int]) -> Optional[int]:
    if label in address_map:
        return address_map[label]

    folded = {name.upper(): ea for name, ea in address_map.items()}
    return folded.get(label.upper())


def find_next_instruction_address(lines: List[str], start_index: int) -> Optional[int]:
    for line in lines[start_index + 1 :]:
        match = ASM_ADDR_RE.match(line)
        if match:
            return int(match.group("addr"), 16)
    return None


def strip_cpp_line_comment(line: str) -> str:
    return line.split("//", 1)[0]


def collect_breakpoints_for_file(path: pathlib.Path, address_map: Dict[str, int]) -> List[BreakpointEntry]:
    lines = path.read_text(errors="ignore").splitlines()
    entries: List[BreakpointEntry] = []

    for index, line in enumerate(lines):
        match = VALIDATE_RE.search(strip_cpp_line_comment(line))
        if not match:
            continue

        label = match.group("label")
        variable_name = match.group("var")
        next_instruction_address = find_next_instruction_address(lines, index)
        if next_instruction_address is None:
            raise ValueError(
                f"{path}:{index + 1}: could not find next original instruction address after mame_validate_word"
            )

        variable_address = lookup_label_address(label, address_map)
        if variable_address is None:
            raise ValueError(f"{path}:{index + 1}: label {label!r} not found in address map")

        entries.append(
            BreakpointEntry(
                label=label,
                variable_name=variable_name,
                variable_address=variable_address,
                next_instruction_address=next_instruction_address,
                source_path=path,
                source_line=index + 1,
            )
        )

    return entries


def collect_breakpoints(source_root: pathlib.Path, address_map: Dict[str, int]) -> List[BreakpointEntry]:
    entries: List[BreakpointEntry] = []
    for path in sorted(source_root.rglob("*.c")):
        entries.extend(collect_breakpoints_for_file(path, address_map))
    return entries


def render_output(entries: Iterable[BreakpointEntry]) -> str:
    entry_list = list(entries)
    rows = [
        "# Autogenerated by tools/mame/generate_mame_validate_breakpoints.py",
        "# Format: bpset <next instr>, 1, { logerror \"<label>: %d\", d<addr>; }",
    ]
    for index, entry in enumerate(entry_list):
        action = "quit" if index == len(entry_list) - 1 else "g"
        rows.append(entry.format_mame(action=action))
    rows.append("")
    return "\n".join(rows) + "g"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate MAME debugger breakpoints for mame_validate_word call sites."
    )
    parser.add_argument(
        "--source-root",
        type=pathlib.Path,
        default=ROOT / "src",
        help="Root directory to scan for C sources (default: %(default)s)",
    )
    parser.add_argument(
        "--address-map",
        type=pathlib.Path,
        default=ROOT / "tools" / "ida" / "address.map",
        help="Path to tools/ida/address.map (default: %(default)s)",
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=ROOT / "tools" / "mame" / "output" / "mame_validate_word_breakpoints.txt",
        help="Output debugger command file (default: %(default)s)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    address_map = parse_address_map(args.address_map)
    entries = collect_breakpoints(args.source_root, address_map)
    output = render_output(entries)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output)
    print(f"wrote {len(entries)} breakpoint entries to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
