#!/usr/bin/env python3
"""Build a standalone IDAPython script that only applies DP=0 marks."""

from __future__ import annotations

import pathlib
from typing import List


def parse_int(s: str) -> int:
    s = s.strip()
    if s.lower().startswith("0x"):
        return int(s, 16)
    return int(s, 10)


def load_dp0_marks(path: pathlib.Path) -> List[int]:
    out: List[int] = []
    with path.open(newline="") as f:
        for ln in f:
            s = ln.strip()
            if not s or s.startswith("#") or s.lower() == "address":
                continue
            out.append(parse_int(s))
    return sorted(set(out))


def emit_script(dp0_marks: List[int]) -> str:
    lines: List[str] = []
    lines.append("# Auto-generated by tools/ida/build_ida_dp0_script.py")
    lines.append("# Applies only DP=0 segment-register assumptions.")
    lines.append("import ida_idp")
    lines.append("import ida_segment")
    lines.append("import ida_segregs")
    lines.append("")
    lines.append("DP0_MARKS = [")
    for ea in dp0_marks:
        lines.append(f"    0x{ea:08X},")
    lines.append("]")
    lines.append("")
    lines.append("def in_mapped(ea):")
    lines.append("    return ida_segment.getseg(ea) is not None")
    lines.append("")
    lines.append("def dp_reg_index():")
    lines.append("    if hasattr(ida_idp, 'str2reg'):")
    lines.append("        idx = ida_idp.str2reg('dp')")
    lines.append("        if idx >= 0:")
    lines.append("            return idx")
    lines.append("    names = getattr(ida_idp.ph, 'reg_names', [])")
    lines.append("    for i, name in enumerate(names):")
    lines.append("        if str(name).lower() == 'dp':")
    lines.append("            return i")
    lines.append("    return -1")
    lines.append("")
    lines.append("def apply_dp0():")
    lines.append("    dp_reg = dp_reg_index()")
    lines.append("    if dp_reg < 0:")
    lines.append("        raise RuntimeError('could not resolve TMS320C3 dp register index')")
    lines.append("    applied = 0")
    lines.append("    skipped = 0")
    lines.append("    failed = 0")
    lines.append("    for ea in DP0_MARKS:")
    lines.append("        if not in_mapped(ea):")
    lines.append("            skipped += 1")
    lines.append("            continue")
    lines.append("        ok = ida_segregs.split_sreg_range(ea, dp_reg, 0, ida_segregs.SR_user, False)")
    lines.append("        if ok:")
    lines.append("            applied += 1")
    lines.append("        else:")
    lines.append("            failed += 1")
    lines.append("            print('[crusnusa-dp0] failed at 0x%08X' % ea)")
    lines.append("    print('[crusnusa-dp0] applied=%d skipped=%d failed=%d total=%d' % (applied, skipped, failed, len(DP0_MARKS)))")
    lines.append("")
    lines.append("apply_dp0()")
    lines.append("")
    return "\n".join(lines)


def build_dp0_script(
    dp0_tsv: pathlib.Path = pathlib.Path(__file__).resolve().parent / "log" / "romlst_dp0.tsv",
    out: pathlib.Path = pathlib.Path(__file__).resolve().parent / "ida_dp0_import.py",
) -> int:
    marks = load_dp0_marks(dp0_tsv)
    out.write_text(emit_script(marks))
    return len(marks)


if __name__ == "__main__":
    n = build_dp0_script()
    print(f"wrote {pathlib.Path(__file__).resolve().parent / 'ida_dp0_import.py'} dp0_marks={n}")
