#!/usr/bin/env python3
"""Generate a standalone IDAPython label-apply script with embedded data.

Input:
  --labels-tsv tools/ida/romlst_labels.tsv
  --out tools/ida/apply_romlst_labels.py
Optional:
  --dp0-tsv tools/ida/romlst_dp0.tsv
"""

from __future__ import annotations

import argparse
import csv
import pathlib
import re
from dataclasses import dataclass
from typing import Dict, List, Set, Tuple


@dataclass(frozen=True)
class LabelRow:
    raw_label: str
    norm_label: str
    module: str
    kind: str
    address: int
    status: str


def parse_int(s: str) -> int:
    s = s.strip()
    if s.lower().startswith("0x"):
        return int(s, 16)
    return int(s, 10)


def sanitize_ida_name(name: str) -> str:
    out = re.sub(r"[^A-Za-z0-9_.$?@]", "_", name)
    if not out:
        out = "lbl"
    if out[0].isdigit():
        out = "_" + out
    return out


def load_labels(path: pathlib.Path) -> List[LabelRow]:
    rows: List[LabelRow] = []
    with path.open(newline="") as f:
        r = csv.DictReader(f, delimiter="\t")
        for rec in r:
            status = (rec.get("status") or "").strip()
            if status != "OK":
                continue
            addr_s = (rec.get("address") or "").strip()
            if not addr_s:
                continue
            raw_label = (rec.get("label") or "").strip()
            if raw_label.startswith("$"):
                continue
            addr = parse_int(addr_s)
            norm_label = (rec.get("label_norm") or raw_label).strip()
            module = (rec.get("module") or "").strip()
            kind = (rec.get("kind") or "code").strip().lower()
            rows.append(
                LabelRow(
                    raw_label=raw_label,
                    norm_label=norm_label,
                    module=module,
                    kind=kind,
                    address=addr,
                    status=status,
                )
            )
    return rows


def load_dp0_marks(path: pathlib.Path | None) -> List[int]:
    out: List[int] = []
    if path is None:
        return out
    with path.open(newline="") as f:
        for ln in f:
            s = ln.strip()
            if not s or s.startswith("#") or s.lower() == "address":
                continue
            out.append(parse_int(s))
    return sorted(set(out))


def load_comments(path: pathlib.Path | None) -> List[Tuple[int, str]]:
    out: List[Tuple[int, str]] = []
    if path is None or not path.exists():
        return out
    with path.open(newline="") as f:
        r = csv.DictReader(f, delimiter="\t")
        for rec in r:
            a = (rec.get("address") or "").strip()
            c = (rec.get("comment") or "").strip()
            if not a or not c:
                continue
            out.append((parse_int(a), c))
    return out


def choose_unique_names(rows: List[LabelRow]) -> List[Tuple[int, str, str]]:
    used: Set[str] = set()
    out: List[Tuple[int, str, str]] = []
    by_addr: Dict[int, List[LabelRow]] = {}
    for r in rows:
        by_addr.setdefault(r.address, []).append(r)

    for addr in sorted(by_addr.keys()):
        group = by_addr[addr]

        def score(r: LabelRow) -> Tuple[int, int, int, int]:
            is_global = 1 if not r.module and "@" not in r.norm_label else 0
            has_at = 1 if "@" in r.norm_label else 0
            rom_alias = 1 if re.search(r"_[A-Z0-9]+$", r.norm_label) else 0
            is_sub = 1 if r.norm_label.lower().startswith("sub_") else 0
            return (is_global, has_at, -rom_alias, -is_sub)

        best = sorted(group, key=score, reverse=True)[0]
        base = sanitize_ida_name(best.norm_label)
        candidate = base
        i = 2
        while candidate in used:
            candidate = f"{base}_{i}"
            i += 1
        used.add(candidate)
        out.append((addr, candidate, best.kind))
    return out


def emit_script(labels: List[Tuple[int, str, str]], dp0_marks: List[int], comments: List[Tuple[int, str]]) -> str:
    lines: List[str] = []
    lines.append("# Auto-generated by tools/ida/generate_spider_labels_py.py")
    lines.append("import ida_name")
    lines.append("import ida_bytes")
    lines.append("import ida_funcs")
    lines.append("import ida_segregs")
    lines.append("import ida_idp")
    lines.append("import ida_segment")
    lines.append("import ida_kernwin")
    lines.append("import idautils")
    lines.append("")
    lines.append("LABELS = [")
    for ea, nm, _kind in labels:
        lines.append(f'    (0x{ea:08X}, "{nm}"),')
    lines.append("]")
    lines.append("")
    lines.append("DP0_MARKS = [")
    for ea in sorted(dp0_marks):
        lines.append(f"    0x{ea:08X},")
    lines.append("]")
    lines.append("")
    lines.append("COMMENTS = [")
    for ea, c in comments:
        c2 = c.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    (0x{ea:08X}, "{c2}"),')
    lines.append("]")
    lines.append("")
    lines.append("VEC_NAMES = {")
    lines.append('    0x00: "vec_reset__c_int00",')
    lines.append('    0x01: "vec_int0_display",')
    lines.append('    0x02: "vec_int1_tv30",')
    lines.append('    0x03: "vec_int2_comm",')
    lines.append('    0x04: "vec_int3_atod",')
    lines.append('    0x05: "vec_xint0",')
    lines.append('    0x06: "vec_rint0",')
    lines.append('    0x07: "vec_xint1",')
    lines.append('    0x08: "vec_rint1",')
    lines.append('    0x09: "vec_tint0",')
    lines.append('    0x0A: "vec_tint1",')
    lines.append('    0x0B: "vec_dint",')
    lines.append("}")
    lines.append("")
    lines.append("def in_mapped(ea):")
    lines.append("    return ida_segment.getseg(ea) is not None")
    lines.append("")
    lines.append("def bswap32(v):")
    lines.append("    return ((v & 0xFF) << 24) | (((v >> 8) & 0xFF) << 16) | (((v >> 16) & 0xFF) << 8) | ((v >> 24) & 0xFF)")
    lines.append("")
    lines.append("def maybe_make_func(ea):")
    lines.append("    if not in_mapped(ea):")
    lines.append("        return False")
    lines.append("    if ida_funcs.get_func(ea):")
    lines.append("        return True")
    lines.append("    return bool(ida_funcs.add_func(ea))")
    lines.append("")
    lines.append("def clear_all_names():")
    lines.append("    c = 0")
    lines.append("    for ea, _nm in list(idautils.Names()):")
    lines.append("        ida_name.del_local_name(ea)")
    lines.append("        ida_name.del_global_name(ea)")
    lines.append("        c += 1")
    lines.append("    return c")
    lines.append("")
    lines.append("def apply():")
    lines.append("    cleared = clear_all_names()")
    lines.append("    named = 0")
    lines.append("    vec_named = 0")
    lines.append("    vec_funcs = 0")
    lines.append("    dp_set = 0")
    lines.append("")
    lines.append("    # Vector labels and targets")
    lines.append("    for idx in range(0x40):")
    lines.append("        ea = idx")
    lines.append("        if not in_mapped(ea):")
    lines.append("            continue")
    lines.append('        vname = VEC_NAMES.get(idx, f\"vec_{idx:02X}\")')
    lines.append("        ida_name.set_name(ea, vname, ida_name.SN_FORCE)")
    lines.append("        vec_named += 1")
    lines.append("        target = bswap32(ida_bytes.get_wide_byte(ea))")
    lines.append('        tname = f\"{vname}_target_{target:08X}\"')
    lines.append("        if in_mapped(target):")
    lines.append("            ida_name.set_name(target, tname, ida_name.SN_FORCE)")
    lines.append("            if maybe_make_func(target):")
    lines.append("                vec_funcs += 1")
    lines.append("")
    lines.append("    # Resolve DP register index once (IDA 7.x API expects register index).")
    lines.append('    dp_reg = ida_idp.str2reg("dp")')
    lines.append("    if dp_reg < 0:")
    lines.append('        print("[crusnusa-py] warning: could not resolve dp register index; skipping DP marks")')
    lines.append("")
    lines.append("    # Apply DP=0 splits")
    lines.append("    for ea in DP0_MARKS:")
    lines.append("        if not in_mapped(ea):")
    lines.append("            continue")
    lines.append("        if dp_reg < 0:")
    lines.append("            continue")
    lines.append("        ok = ida_segregs.split_sreg_range(ea, dp_reg, 0, ida_segregs.SR_user, False)")
    lines.append("        if ok:")
    lines.append("            dp_set += 1")
    lines.append("        else:")
    lines.append('            print(f\"[crusnusa-py] dp0 split failed at 0x{ea:08X}\")')
    lines.append("")
    lines.append("    # Apply labels")
    lines.append("    for ea, nm in LABELS:")
    lines.append("        if not in_mapped(ea):")
    lines.append("            continue")
    lines.append("        ida_name.set_name(ea, nm, ida_name.SN_FORCE)")
    lines.append("        named += 1")
    lines.append("")
    lines.append("    # Attach source-macro comments")
    lines.append("    for ea, cmt in COMMENTS:")
    lines.append("        if not in_mapped(ea):")
    lines.append("            continue")
    lines.append("        ida_bytes.set_cmt(ea, cmt, 0)")
    lines.append("")
    lines.append('    print(f\"[crusnusa-py] cleared={cleared} vectors={vec_named} vec_funcs={vec_funcs} dp0={dp_set} labels={named} comments={len(COMMENTS)}\")')
    lines.append("")
    lines.append("apply()")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--labels-tsv", required=True, type=pathlib.Path)
    ap.add_argument("--out", required=True, type=pathlib.Path)
    ap.add_argument("--dp0-tsv", type=pathlib.Path, default=None)
    ap.add_argument("--comments-tsv", type=pathlib.Path, default=None)
    args = ap.parse_args()

    rows = load_labels(args.labels_tsv)
    labels = choose_unique_names(rows)
    dp0_path = args.dp0_tsv
    if dp0_path is None:
        dp0_path = args.labels_tsv.with_name(args.labels_tsv.stem.replace("_labels", "_dp0") + args.labels_tsv.suffix)
    dp0_marks = load_dp0_marks(dp0_path if dp0_path.exists() else None)
    comments = load_comments(args.comments_tsv)
    text = emit_script(labels, dp0_marks, comments)
    args.out.write_text(text)
    print(f"wrote {args.out}")
    print(f"labels={len(labels)} dp0_marks={len(dp0_marks)} comments={len(comments)}")


if __name__ == "__main__":
    main()
