#!/usr/bin/env python3
"""Generate the C sound-entry table from the original SNDTAB.INC."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "asm" / "SNDTAB.INC"
OUTPUT = ROOT / "src" / "game" / "sndtaba.c"

SYMBOLS = {"FRAMES": 0x10000, "CHAN0": 0, "CHAN1": 0x100,
           "CHAN2": 0x200, "CHAN3": 0x300, "NINT": 0x1000,
           "ENINT": 0x2000, "SPEECH": 0x20FF}


def value(expression: str) -> int:
    expression = expression.strip()
    expression = re.sub(r"(?i)\b([0-9a-f]+)h\b", r"0x\1", expression)
    expression = re.sub(r"\b0+([0-9]+)\b", r"\1", expression)
    for name, replacement in SYMBOLS.items():
        expression = re.sub(rf"\b{name}\b", str(replacement), expression)
    if not re.fullmatch(r"[0-9a-fA-FxX|*+() \t-]+", expression):
        raise ValueError(f"unsupported expression: {expression}")
    return int(eval(expression, {"__builtins__": {}}, {}))


words = []
for line in SOURCE.read_text().splitlines():
    match = re.match(r"\s*\.word\s+([^;]+)", line, re.IGNORECASE)
    if match:
        words.append(value(match.group(1)))

if len(words) % 3 != 0 or any(words[i] != 0 for i in range(2, len(words), 3)):
    raise SystemExit("SNDTAB.INC no longer contains single-command three-word entries")

lines = [
    '#include "sndtaba.h"', '',
    '/* Generated by tools/generate_sndtaba.py from asm/SNDTAB.INC. */',
    'static const crusn_sound_entry SNDTAB[] = {',
]
for i in range(0, len(words), 3):
    priority, packed, _ = words[i:i + 3]
    lines.append(f"    {{ 0x{priority:04X}, {packed >> 16}, {packed & 0x7FFF} }},")
lines += [
    '};', '',
    'const crusn_sound_entry* crusn_sound_entry_from_index(int sound_index) {',
    '    if (sound_index < 0 || sound_index % 3 != 0',
    '        || (size_t)(sound_index / 3) >= crusn_sound_entry_count()) return 0;',
    '    return &SNDTAB[sound_index / 3];',
    '}', '',
    'size_t crusn_sound_entry_count(void) {',
    '    return sizeof(SNDTAB) / sizeof(SNDTAB[0]);',
    '}', '',
]
OUTPUT.write_text("\n".join(lines))
