#!/usr/bin/env python3
"""Generate the readable C sound table from the original STABLE.INC."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "asm" / "STABLE.INC"
GENERATED_ASM = ROOT / "asm" / "SNDTAB.INC"
OUTPUT = ROOT / "src" / "game" / "sndtaba.c"

SYMBOLS = {"FRAMES": 0x10000, "CHAN0": 0, "CHAN1": 0x100,
           "CHAN2": 0x200, "CHAN3": 0x300, "NINT": 0x1000,
           "ENINT": 0x2000, "SPEECH": 0x20FF}


def value(expression: str) -> int:
    expression = expression.strip()
    expression = re.sub(r"(?i)\b([0-9a-f]+)h\b", r"0x\1", expression)
    expression = re.sub(r"\b0+([0-9]+)\b", r"\1", expression)
    for name, replacement in SYMBOLS.items():
        expression = re.sub(rf"\b{name}\b", str(replacement), expression)
    if not re.fullmatch(r"[0-9a-fA-FxX|*+() \t-]+", expression):
        raise ValueError(f"unsupported expression: {expression}")
    return int(eval(expression, {"__builtins__": {}}, {}))


def c_expression(expression: str) -> str:
    expression = expression.strip()
    expression = re.sub(r"(?i)\b([0-9a-f]+)h\b", r"0x\1", expression)
    expression = re.sub(r"\b0+([0-9]+)\b", r"\1", expression)
    expression = re.sub(r"\s*\|\s*", " | ", expression)
    expression = re.sub(r"\s*\*\s*", " * ", expression)
    return expression


def sond_match(line: str):
    return re.match(
        r"\s*SOND\s+([^,]+),([^,]+),([^;]+?)(?:\s*;\s*(.*))?$",
        line,
        re.IGNORECASE,
    )


entries = []
for line in SOURCE.read_text().splitlines():
    match = sond_match(line)
    if match:
        name, priority, packed, _ = match.groups()
        entries.append((name.strip(), value(priority), value(packed)))

generated_words = []
for line in GENERATED_ASM.read_text().splitlines():
    match = re.match(r"\s*\.word\s+([^;]+)", line, re.IGNORECASE)
    if match:
        generated_words.append(value(match.group(1)))

stable_words = []
for _, priority, packed in entries:
    stable_words.extend((priority, packed, 0))

if stable_words != generated_words:
    raise SystemExit("STABLE.INC entries no longer match generated SNDTAB.INC")

lines = [
    '#include "sndtaba.h"',
    '',
    '#include "sndtab.h"',
    '#include "sys.h"',
    '',
    '/* Generated by tools/generate_sndtaba.py from asm/STABLE.INC. */',
    '#define FRAMES 0x10000u',
    '#define SPEECH (0x00ff | ENINT | CHAN1)',
    '#define SOND(name, priority, time_and_code) \\',
    '    [(name) / 3] = { (priority), (time_and_code) >> 16, \\',
    '        (time_and_code) & 0x7fff }',
    '',
    'static const crusn_sound_entry SOUND_TABLE[] = {',
]

for source_line in SOURCE.read_text().splitlines():
    match = sond_match(source_line)
    if match:
        name, priority, packed, comment = match.groups()
        output_line = (
            f"    SOND({name.strip()}, {c_expression(priority)}, "
            f"{c_expression(packed)}),"
        )
        if comment:
            output_line += f" // {comment.strip()}"
        lines.append(output_line)
        continue

    stripped = source_line.strip()
    if stripped.startswith(';'):
        commented_match = sond_match(stripped[1:])
        if commented_match:
            name, priority, packed, comment = commented_match.groups()
            output_line = (
                f"    // SOND({name.strip()}, {c_expression(priority)}, "
                f"{c_expression(packed)})"
            )
            if comment:
                output_line += f"; {comment.strip()}"
            lines.append(output_line)
        else:
            lines.append(f"    //{stripped[1:]}")
    elif stripped.startswith('*'):
        lines.append(f"    //{stripped[1:]}")
    elif not stripped:
        lines.append('')
    else:
        raise SystemExit(f"unsupported STABLE.INC line: {source_line}")

lines += [
    '};',
    '',
    '#undef SOND',
    '#undef SPEECH',
    '#undef FRAMES',
    '',
    'const crusn_sound_entry* crusn_sound_entry_from_index(int sound_index) {',
    '    if (sound_index < 0 || sound_index % 3 != 0',
    '        || (size_t)(sound_index / 3) >= crusn_sound_entry_count()) return 0;',
    '    return &SOUND_TABLE[sound_index / 3];',
    '}',
    '',
    'const crusn_sound_entry* crusn_sound_entry_from_dcs_track(unsigned dcs_track,',
    '                                                          int* channel) {',
    '    size_t entry_index;',
    '',
    '    for (entry_index = 0; entry_index < crusn_sound_entry_count(); ++entry_index) {',
    '        if (SOUND_TABLE[entry_index].dcs_track == dcs_track) {',
    '            *channel = (int)((SOUND_TABLE[entry_index].priority_word >> 8) & 0x0f);',
    '            return &SOUND_TABLE[entry_index];',
    '        }',
    '    }',
    '',
    '    /* SNDFX selects its second effects channel by incrementing the command. */',
    '    for (entry_index = 0; entry_index < crusn_sound_entry_count(); ++entry_index) {',
    '        int entry_channel = (int)((SOUND_TABLE[entry_index].priority_word >> 8) & 0x0f);',
    '        if (entry_channel == 1 && SOUND_TABLE[entry_index].dcs_track + 1 == dcs_track) {',
    '            *channel = 2;',
    '            return &SOUND_TABLE[entry_index];',
    '        }',
    '    }',
    '',
    '    return 0;',
    '}',
    '',
    'size_t crusn_sound_entry_count(void) {',
    '    return sizeof(SOUND_TABLE) / sizeof(SOUND_TABLE[0]);',
    '}',
    '',
]
OUTPUT.write_text("\n".join(lines))
